# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/proxyAudit/proxyserverCancle_query.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseProxyservercancleQuery(HttpRunner):

    config = Config("企业用户取消托管后查询托管信息").base_url("${ENV(HOST)}").verify(False)

    teststeps = [
        Step(
            RunRequest("/api/prefixProxy/pageQuery")
            .get("/api/prefixProxy/pageQuery")
            .with_params(
                **{
                    "cache": "1664333881101",
                    "currentPage": "1",
                    "entPrefix": "$prefix",
                    "order": "",
                    "orderProp": "",
                }
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"SESSION": "$entSession"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.message", "success")
            .assert_equal("body.status", 1)
            .assert_equal("body.data.content[0].proxyState", 1)
        ),
    ]


if __name__ == "__main__":
    TestCaseProxyservercancleQuery().test_start()
