# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/proxyAudit/proxyauditRejectDetail.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseProxyauditrejectdetail(HttpRunner):

    config = Config("托管审核驳回详情").base_url("${ENV(HOST)}")

    teststeps = [
        Step(
            RunRequest("/api/proxyserver/prefix/audit/detail")
            .get("/api/proxyserver/prefix/audit/detail")
            .with_params(
                **{
                    "Id": "$prefixauditid",
                    "cache": "1664274365563",
                    "isSensetive": "1",
                    "type": "detail",
                }
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"SESSION": "$entSession"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.message", "success")
            .assert_equal("body.status", 1)
            .assert_equal("body.data.proxyServerPrefixAuditPO[0].status", 3)
            .assert_contains("body.data.proxyServerPrefixAuditPO[0].auditMsg", "被驳回")
        ),
    ]


if __name__ == "__main__":
    TestCaseProxyauditrejectdetail().test_start()
