# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/proxyAudit/proxyserverdetail.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseProxyserverdetail(HttpRunner):

    config = Config("获取托管服务器信息").base_url("${ENV(HOST)}").verify(False)

    teststeps = [
        Step(
            RunRequest("获取托管服务器信息")
            .get("/api/proxyserver/prefix/audit/detail")
            .with_params(
                **{
                    "Id": "$prefixauditid",
                    "cache": "1663918468590",
                    "isSensetive": "1",
                    "type": "detail",
                }
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"SESSION": "$session"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.message", "success")
            .assert_equal("body.status", 1)
            .assert_equal("body.data.handleProxyServerPO[0].id", "$proxyserverid")
        ),
    ]


if __name__ == "__main__":
    TestCaseProxyserverdetail().test_start()
