# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/template/templateUpdate.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseTemplateupdate(HttpRunner):

    config = Config("数据模板更新").base_url("${ENV(HOST)}").verify(False)

    teststeps = [
        Step(
            RunRequest("数据模板更新")
            .post("/api/v5/identity/template")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "849",
                    "Content-Type": "application/json",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                    "X-HTTP-Method-Override": "put",
                }
            )
            .with_cookies(**{"SESSION": "$entSession"})
            .with_json(
                {
                    "description": "test",
                    "handle": "$handle",
                    "id": 4367,
                    "industryCategory": "C",
                    "industrySpecific": "15",
                    "industrySubclass": "1530",
                    "industryTrade": "153",
                    "items": [
                        {
                            "authorizationKey": "",
                            "idIndex": 2000,
                            "idType": "terminalType",
                            "metadata": {
                                "maxLength": 65536,
                                "minLength": 0,
                                "type": "string",
                            },
                            "metadataId": 20418,
                            "name": "终端类型",
                            "required": False,
                            "state": 1,
                        },
                        {
                            "authorizationKey": "",
                            "idIndex": 2001,
                            "idType": "subject",
                            "metadata": {
                                "maxLength": 65536,
                                "minLength": 0,
                                "type": "string",
                            },
                            "metadataId": 20419,
                            "name": "所属主体",
                            "required": False,
                            "state": 1,
                        },
                        {
                            "authorizationKey": "",
                            "idIndex": 2002,
                            "idType": "useFor",
                            "metadata": {
                                "maxLength": 65536,
                                "minLength": 0,
                                "type": "string",
                            },
                            "metadataId": 20420,
                            "name": "用途",
                            "required": False,
                            "state": 1,
                        },
                        {
                            "authorizationKey": "",
                            "idIndex": 2003,
                            "idType": "serOrImei",
                            "metadata": {
                                "maxLength": 65536,
                                "minLength": 0,
                                "type": "string",
                            },
                            "metadataId": 20421,
                            "name": "串号或IMEI",
                            "required": False,
                            "state": 1,
                        },
                        {
                            "authorizationKey": "",
                            "idIndex": 2004,
                            "idType": "licenseNo",
                            "metadata": {
                                "maxLength": 10000,
                                "minLength": 0,
                                "type": "string",
                            },
                            "metadataId": 20422,
                            "name": "进网许可证编号模板更新验证",
                            "required": False,
                            "state": 1,
                        },
                        {
                            "authorizationKey": "",
                            "idIndex": 2005,
                            "idType": "licenseSign",
                            "metadata": {
                                "maxLength": 65536,
                                "minLength": 0,
                                "type": "string",
                            },
                            "metadataId": 20423,
                            "name": "进网许可标志序号",
                            "required": False,
                            "state": 1,
                        },
                        {
                            "authorizationKey": "",
                            "idIndex": 2006,
                            "idType": "autotest",
                            "metadata": {
                                "maxLength": 10000,
                                "minLength": 0,
                                "type": "string",
                            },
                            "metadataId": 20424,
                            "name": "数据模板测试",
                            "required": False,
                            "state": 1,
                        },
                    ],
                    "prefix": "${prefix}",
                    "type": 1,
                    "version": "${version}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.message", "success")
            .assert_equal("body.status", 1)
            .assert_equal("body.data", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseTemplateupdate().test_start()
