# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/template/templateDetail.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseTemplatedetail(HttpRunner):

    config = Config("数据模板删除").base_url("${ENV(HOST)}").verify(False)

    teststeps = [
        Step(
            RunRequest("数据模板删除")
            .get("/api/v5/identity/template/detail")
            .with_params(**{"cache": "1663816969447", "id": "${template_id}"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"SESSION": "$entSession"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.message", "success")
            .assert_equal("body.status", 1)
            .assert_contained_by("body.status", [1, 200])
        ),
    ]


if __name__ == "__main__":
    TestCaseTemplatedetail().test_start()
