# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/template/templateDelete.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseTemplatedelete(HttpRunner):

    config = (
        Config("数据模板删除")
        .variables(
            **{"template_id": "3", "username": "admin22", "password": "Admin@123"}
        )
        .base_url("${ENV(HOST)}")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("数据模板删除")
            .post("/api/v5/identity/template")
            .with_params(**{"id": "${template_id}"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                    "X-HTTP-Method-Override": "delete",
                }
            )
            .with_cookies(**{"SESSION": "$entSession"})
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.message", "success")
            .assert_equal("body.status", 1)
            .assert_equal("body.data", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseTemplatedelete().test_start()
