# NOTE: Generated By HttpRunner v3.1.6
# FROM: testsuites/entapply/store_second.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.prefixAudit.register_test import TestCaseRegister as Register

from testcases.login.login_ent_test import TestCaseLoginEnt as LoginEnt

from testcases.prefixAudit.register.upload_img_test import (
    TestCaseUploadImg as UploadImg,
)

from testcases.prefixAudit.register.upload_img_f_test import (
    TestCaseUploadImgF as UploadImgF,
)

from testcases.prefixAudit.register.upload_img_b_test import (
    TestCaseUploadImgB as UploadImgB,
)

from testcases.prefixAudit.register.submit_first_test import (
    TestCaseSubmitFirst as SubmitFirst,
)

from testcases.prefixAudit.register.apply_or_not_test import (
    TestCaseApplyOrNot as ApplyOrNot,
)

from testcases.entapply.store_second_test import TestCaseStoreSecond as StoreSecond


class TestCaseStoreSecond(HttpRunner):

    config = Config("企业注册第二步信息暂存用例集2").variables(
        **{
            "username": "${get_username()}",
            "entaccount": "$username",
            "entpassword": "${ENV(entpassword)}",
            "entSession": "${get_session(entaccount, entpassword)}",
            "email": "${get_email()}",
            "mobile": "${get_mobile()}",
            "account": "${ENV(adminaccount)}",
            "password": "${ENV(adminpassword)}",
            "prefix": "${ENV(prefix_second)}${get_random_param(1000,10000000000,1)}",
            "personId": "${get_idcardno()}",
        }
    )

    teststeps = [
        Step(RunTestCase("用户注册").call(Register)),
        Step(RunTestCase("登录-企业").call(LoginEnt).export(*["entSession"])),
        Step(RunTestCase("前缀注册企业资质图片上传").call(UploadImg).export(*["imgId"])),
        Step(RunTestCase("前缀注册企业联系人身份证图片正面上传").call(UploadImgF).export(*["imgId_f"])),
        Step(RunTestCase("前缀注册企业联系人身份证图片背面上传").call(UploadImgB).export(*["imgId_b"])),
        Step(RunTestCase("企业注册第一步提交信息").call(SubmitFirst)),
        Step(
            RunTestCase("企业注册查询注册信息")
            .call(ApplyOrNot)
            .export(
                *[
                    "entInfoSyss_2_deployAddr",
                    "orgAddrCountyDesc",
                    "entInfoSyss_3_deployAddrCity",
                    "entInfoSyss_3_deployAddrCounty",
                    "legalCrtTypeDesc",
                    "entInfoSyss_0_entApplyId",
                    "orgCategorySpecificDesc",
                    "legalCrtNo",
                    "entInfoSyss_3_entApplyId",
                    "entInfoSyss_0_sysType",
                    "orgAddrCityDesc",
                    "entUserId",
                    "entInfoSyss_3_id",
                    "entInfoSyss_2_deployMode",
                    "entInfoSyss_0_deployAddrCounty",
                    "orgAddrCity",
                    "entInfoSyss_0_deployAddrProvince",
                    "entInfoSyss_2_id",
                    "entId",
                    "entInfoSyss_3_deployAddrProvince",
                    "entInfoSyss_0_id",
                    "orgCrtCode",
                    "orgNatureDesc",
                    "imgId_f",
                    "entInfoSyss_0_deployAddrCity",
                    "entInfoSyss_1_deployAddr",
                    "entInfoSyss_1_entApplyId",
                    "userId",
                    "legalEmail",
                    "legalCrtFrontImgRid",
                    "orgAddrProvinceDesc",
                    "entInfoSyss_3_sysType",
                    "entInfoSyss_2_deployAddrProvince",
                    "createDate",
                    "entInfoSyss_1_deployAddrCounty",
                    "contactEmail",
                    "userName",
                    "legalName",
                    "orgName",
                    "entApplyId",
                    "entInfoSyss_1_deployMode",
                    "entInfoSyss_2_entApplyId",
                    "entInfoSyss_1_sysType",
                    "entInfoSyss_0_deployAddr",
                    "entInfoSyss_3_deployAddr",
                    "entInfoSyss_3_deployMode",
                    "entInfoSyss_1_deployAddrProvince",
                    "contactCrtNo",
                    "legalCrtType",
                    "legalCrtBackImgRid",
                    "contactCrtType",
                    "updateDate",
                    "orgAddrCounty",
                    "orgCrtImgRid",
                    "contactPhone",
                    "entInfoSyss_1_id",
                    "industrySpecific",
                    "orgAddr",
                    "entInfoSyss_1_deployAddrCity",
                    "orgNature",
                    "orgCrtType",
                    "entInfoSyss_2_deployAddrCounty",
                    "imgId",
                    "legalPhone",
                    "entInfoSyss_0_deployMode",
                    "entInfoSyss_2_sysType",
                    "entInfoSyss_2_deployAddrCity",
                    "industryCategory",
                    "imgId_b",
                    "contactName",
                    "prefix",
                    "orgAddrProvince",
                    "applyId",
                ]
            )
        ),
        Step(RunTestCase("暂存企业注册第二步提交信息").call(StoreSecond)),
    ]


if __name__ == "__main__":
    TestCaseStoreSecond().test_start()
