# NOTE: Generated By HttpRunner v3.1.6
# FROM: testsuites/entapply/update.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.prefixAudit.register_test import TestCaseRegister as Register

from testcases.login.login_ent_test import TestCaseLoginEnt as LoginEnt

from testcases.prefixAudit.register.upload_img_test import (
    TestCaseUploadImg as UploadImg,
)

from testcases.prefixAudit.register.upload_img_f_test import (
    TestCaseUploadImgF as UploadImgF,
)

from testcases.prefixAudit.register.upload_img_b_test import (
    TestCaseUploadImgB as UploadImgB,
)

from testcases.prefixAudit.register.submit_first_test import (
    TestCaseSubmitFirst as SubmitFirst,
)

from testcases.prefixAudit.register.apply_or_not_test import (
    TestCaseApplyOrNot as ApplyOrNot,
)

from testcases.prefixAudit.register.submit_second_test import (
    TestCaseSubmitSecond as SubmitSecond,
)

from testcases.prefixAudit.register.submit_final_test import (
    TestCaseSubmitFinal as SubmitFinal,
)

from testcases.login.login_admin_test import TestCaseLoginAdmin as LoginAdmin

from testcases.prefixAudit.audit.finance_rule_findRule_test import (
    TestCaseFinanceRuleFindrule as FinanceRuleFindrule,
)

from testcases.prefixAudit.audit.finance_rule_findRule_reg_test import (
    TestCaseFinanceRuleFindruleReg as FinanceRuleFindruleReg,
)

from testcases.prefixAudit.audit.v3_ent_audit_save_test import (
    TestCaseV3EntAuditSave as V3EntAuditSave,
)

from testcases.entapply.apply_or_not_update_before_test import (
    TestCaseApplyOrNotUpdateBefore as ApplyOrNotUpdateBefore,
)

from testcases.entapply.store_first_update_test import (
    TestCaseStoreFirstUpdate as StoreFirstUpdate,
)

from testcases.entapply.update_prefix_test import TestCaseUpdatePrefix as UpdatePrefix

from testcases.entapply.apply_or_not_4_update_test import (
    TestCaseApplyOrNot4Update as ApplyOrNot4Update,
)


class TestCaseUpdate(HttpRunner):

    config = (
        Config("更新已审核通过的企业前缀用例集")
        .variables(
            **{
                "account": "${ENV(adminaccount)}",
                "password": "${ENV(adminpassword)}",
                "username": "${get_username()}",
                "entaccount": "$username",
                "entpassword": "${ENV(entpassword)}",
                "mobile": "${get_mobile()}",
                "email": "${get_email()}",
                "legalNameUpdate": "修改后的名字",
                "orgNameUpdate": "修改后的组织名称",
                "prefix": "${ENV(prefix_second)}${get_random_param(1000,10000000000,1)}",
                "personId": "${get_idcardno()}",
            }
        )
        .export(*["applyId", "prefix", "entPrefix"])
    )

    teststeps = [
        Step(RunTestCase("用户注册").call(Register)),
        Step(RunTestCase("登录-企业").call(LoginEnt).export(*["entSession"])),
        Step(RunTestCase("前缀注册企业资质图片上传").call(UploadImg).export(*["imgId"])),
        Step(RunTestCase("前缀注册企业联系人身份证图片正面上传").call(UploadImgF).export(*["imgId_f"])),
        Step(RunTestCase("前缀注册企业联系人身份证图片背面上传").call(UploadImgB).export(*["imgId_b"])),
        Step(RunTestCase("企业注册第一步提交信息").call(SubmitFirst)),
        Step(
            RunTestCase("企业注册查询注册信息")
            .call(ApplyOrNot)
            .export(
                *[
                    "orgAddrProvinceDesc",
                    "entInfoSyss_2_id",
                    "orgAddrCity",
                    "orgCategorySpecificDesc",
                    "contactCrtNo",
                    "contactEmail",
                    "entInfoSyss_1_deployAddrCounty",
                    "orgAddrCityDesc",
                    "legalCrtTypeDesc",
                    "legalCrtNo",
                    "orgCrtType",
                    "orgNatureDesc",
                    "entInfoSyss_0_entApplyId",
                    "entInfoSyss_3_id",
                    "orgAddr",
                    "updateDate",
                    "industrySpecific",
                    "legalName",
                    "entId",
                    "entInfoSyss_0_deployAddrProvince",
                    "entInfoSyss_3_sysType",
                    "createDate",
                    "entInfoSyss_3_deployAddrCity",
                    "applyId",
                    "entInfoSyss_1_deployAddr",
                    "entInfoSyss_2_deployAddrProvince",
                    "legalPhone",
                    "entInfoSyss_1_sysType",
                    "entInfoSyss_3_deployAddr",
                    "imgId",
                    "entUserId",
                    "prefix",
                    "entInfoSyss_0_deployAddrCounty",
                    "orgNature",
                    "entInfoSyss_1_deployAddrCity",
                    "userId",
                    "imgId_f",
                    "entInfoSyss_3_entApplyId",
                    "contactPhone",
                    "entInfoSyss_2_deployAddr",
                    "entInfoSyss_2_sysType",
                    "legalCrtBackImgRid",
                    "entInfoSyss_0_id",
                    "orgCrtImgRid",
                    "orgName",
                    "entInfoSyss_1_entApplyId",
                    "entInfoSyss_2_entApplyId",
                    "legalCrtFrontImgRid",
                    "entInfoSyss_2_deployAddrCounty",
                    "legalEmail",
                    "entInfoSyss_3_deployMode",
                    "entInfoSyss_3_deployAddrCounty",
                    "imgId_b",
                    "entInfoSyss_0_deployAddr",
                    "industryCategory",
                    "entInfoSyss_3_deployAddrProvince",
                    "entInfoSyss_2_deployAddrCity",
                    "orgAddrCounty",
                    "entInfoSyss_1_deployMode",
                    "entInfoSyss_2_deployMode",
                    "entInfoSyss_0_sysType",
                    "orgAddrCountyDesc",
                    "entApplyId",
                    "legalCrtType",
                    "entInfoSyss_0_deployAddrCity",
                    "entInfoSyss_1_deployAddrProvince",
                    "entInfoSyss_0_deployMode",
                    "contactName",
                    "orgCrtCode",
                    "entInfoSyss_1_id",
                    "orgAddrProvince",
                    "contactCrtType",
                    "userName",
                ]
            )
        ),
        Step(RunTestCase("企业注册第二步提交信息").call(SubmitSecond)),
        Step(
            RunTestCase("企业注册查询注册信息")
            .call(ApplyOrNot)
            .export(
                *[
                    "orgAddrProvinceDesc",
                    "entInfoSyss_2_id",
                    "orgAddrCity",
                    "orgCategorySpecificDesc",
                    "contactCrtNo",
                    "contactEmail",
                    "entInfoSyss_1_deployAddrCounty",
                    "orgAddrCityDesc",
                    "legalCrtTypeDesc",
                    "legalCrtNo",
                    "orgCrtType",
                    "orgNatureDesc",
                    "entInfoSyss_0_entApplyId",
                    "entInfoSyss_3_id",
                    "orgAddr",
                    "updateDate",
                    "industrySpecific",
                    "legalName",
                    "entId",
                    "entInfoSyss_0_deployAddrProvince",
                    "entInfoSyss_3_sysType",
                    "createDate",
                    "entInfoSyss_3_deployAddrCity",
                    "applyId",
                    "entInfoSyss_1_deployAddr",
                    "entInfoSyss_2_deployAddrProvince",
                    "legalPhone",
                    "entInfoSyss_1_sysType",
                    "entInfoSyss_3_deployAddr",
                    "imgId",
                    "entUserId",
                    "prefix",
                    "entInfoSyss_0_deployAddrCounty",
                    "orgNature",
                    "entInfoSyss_1_deployAddrCity",
                    "userId",
                    "imgId_f",
                    "entInfoSyss_3_entApplyId",
                    "contactPhone",
                    "entInfoSyss_2_deployAddr",
                    "entInfoSyss_2_sysType",
                    "legalCrtBackImgRid",
                    "entInfoSyss_0_id",
                    "orgCrtImgRid",
                    "orgName",
                    "entInfoSyss_1_entApplyId",
                    "entInfoSyss_2_entApplyId",
                    "legalCrtFrontImgRid",
                    "entInfoSyss_2_deployAddrCounty",
                    "legalEmail",
                    "entInfoSyss_3_deployMode",
                    "entInfoSyss_3_deployAddrCounty",
                    "imgId_b",
                    "entInfoSyss_0_deployAddr",
                    "industryCategory",
                    "entInfoSyss_3_deployAddrProvince",
                    "entInfoSyss_2_deployAddrCity",
                    "orgAddrCounty",
                    "entInfoSyss_1_deployMode",
                    "entInfoSyss_2_deployMode",
                    "entInfoSyss_0_sysType",
                    "orgAddrCountyDesc",
                    "entApplyId",
                    "legalCrtType",
                    "entInfoSyss_0_deployAddrCity",
                    "entInfoSyss_1_deployAddrProvince",
                    "entInfoSyss_0_deployMode",
                    "contactName",
                    "orgCrtCode",
                    "entInfoSyss_1_id",
                    "orgAddrProvince",
                    "contactCrtType",
                    "userName",
                ]
            )
        ),
        Step(RunTestCase("企业注册最终第三步提交信息").call(SubmitFinal)),
        Step(RunTestCase("登录-管理员").call(LoginAdmin).export(*["adminSession"])),
        Step(
            RunTestCase("年费费用查询").call(FinanceRuleFindrule).export(*["annualFeeRuleId"])
        ),
        Step(
            RunTestCase("注册费费用查询")
            .call(FinanceRuleFindruleReg)
            .export(*["regFeeRuleId"])
        ),
        Step(RunTestCase("审核结果保存").call(V3EntAuditSave)),
        Step(RunTestCase("登录-企业").call(LoginEnt).export(*["entSession"])),
        Step(
            RunTestCase("企业注册查询注册信息")
            .call(ApplyOrNotUpdateBefore)
            .export(
                *[
                    "orgAddrProvinceDesc",
                    "entInfoSyss_2_id",
                    "orgAddrCity",
                    "orgCategorySpecificDesc",
                    "contactCrtNo",
                    "contactEmail",
                    "entInfoSyss_1_deployAddrCounty",
                    "orgAddrCityDesc",
                    "legalCrtTypeDesc",
                    "legalCrtNo",
                    "orgCrtType",
                    "orgNatureDesc",
                    "entInfoSyss_0_entApplyId",
                    "entInfoSyss_3_id",
                    "orgAddr",
                    "updateDate",
                    "industrySpecific",
                    "legalName",
                    "entId",
                    "entInfoSyss_0_deployAddrProvince",
                    "entInfoSyss_3_sysType",
                    "createDate",
                    "entInfoSyss_3_deployAddrCity",
                    "applyId",
                    "entInfoSyss_1_deployAddr",
                    "entInfoSyss_2_deployAddrProvince",
                    "legalPhone",
                    "entInfoSyss_1_sysType",
                    "entInfoSyss_3_deployAddr",
                    "imgId",
                    "entUserId",
                    "entPrefix",
                    "prefix",
                    "entInfoSyss_0_deployAddrCounty",
                    "orgNature",
                    "entInfoSyss_1_deployAddrCity",
                    "userId",
                    "imgId_f",
                    "entInfoSyss_3_entApplyId",
                    "contactPhone",
                    "entInfoSyss_2_deployAddr",
                    "entInfoSyss_2_sysType",
                    "legalCrtBackImgRid",
                    "entInfoSyss_0_id",
                    "orgCrtImgRid",
                    "orgName",
                    "entInfoSyss_1_entApplyId",
                    "entInfoSyss_2_entApplyId",
                    "legalCrtFrontImgRid",
                    "entInfoSyss_2_deployAddrCounty",
                    "legalEmail",
                    "entInfoSyss_3_deployMode",
                    "entInfoSyss_3_deployAddrCounty",
                    "imgId_b",
                    "entInfoSyss_0_deployAddr",
                    "industryCategory",
                    "entInfoSyss_3_deployAddrProvince",
                    "entInfoSyss_2_deployAddrCity",
                    "orgAddrCounty",
                    "entInfoSyss_1_deployMode",
                    "entInfoSyss_2_deployMode",
                    "entInfoSyss_0_sysType",
                    "orgAddrCountyDesc",
                    "entApplyId",
                    "legalCrtType",
                    "entInfoSyss_0_deployAddrCity",
                    "entInfoSyss_1_deployAddrProvince",
                    "entInfoSyss_0_deployMode",
                    "contactName",
                    "orgCrtCode",
                    "entInfoSyss_1_id",
                    "orgAddrProvince",
                    "contactCrtType",
                    "userName",
                ]
            )
        ),
        Step(RunTestCase("前缀注册企业资质图片上传").call(UploadImg).export(*["imgId"])),
        Step(RunTestCase("前缀注册企业联系人身份证图片正面上传").call(UploadImgF).export(*["imgId_f"])),
        Step(RunTestCase("前缀注册企业联系人身份证图片背面上传").call(UploadImgB).export(*["imgId_b"])),
        Step(RunTestCase("暂存企业注册第一步提交信息").call(StoreFirstUpdate)),
        Step(
            RunTestCase("企业注册查询注册信息")
            .call(ApplyOrNot)
            .export(
                *[
                    "orgAddrProvinceDesc",
                    "entInfoSyss_2_id",
                    "orgAddrCity",
                    "orgCategorySpecificDesc",
                    "contactCrtNo",
                    "contactEmail",
                    "entInfoSyss_1_deployAddrCounty",
                    "orgAddrCityDesc",
                    "legalCrtTypeDesc",
                    "legalCrtNo",
                    "orgCrtType",
                    "orgNatureDesc",
                    "entInfoSyss_0_entApplyId",
                    "entInfoSyss_3_id",
                    "orgAddr",
                    "updateDate",
                    "industrySpecific",
                    "legalName",
                    "entId",
                    "entInfoSyss_0_deployAddrProvince",
                    "entInfoSyss_3_sysType",
                    "createDate",
                    "entInfoSyss_3_deployAddrCity",
                    "applyId",
                    "entInfoSyss_1_deployAddr",
                    "entInfoSyss_2_deployAddrProvince",
                    "legalPhone",
                    "entInfoSyss_1_sysType",
                    "entInfoSyss_3_deployAddr",
                    "imgId",
                    "entUserId",
                    "prefix",
                    "entInfoSyss_0_deployAddrCounty",
                    "orgNature",
                    "entInfoSyss_1_deployAddrCity",
                    "userId",
                    "imgId_f",
                    "entInfoSyss_3_entApplyId",
                    "contactPhone",
                    "entInfoSyss_2_deployAddr",
                    "entInfoSyss_2_sysType",
                    "legalCrtBackImgRid",
                    "entInfoSyss_0_id",
                    "orgCrtImgRid",
                    "orgName",
                    "entInfoSyss_1_entApplyId",
                    "entInfoSyss_2_entApplyId",
                    "legalCrtFrontImgRid",
                    "entInfoSyss_2_deployAddrCounty",
                    "legalEmail",
                    "entInfoSyss_3_deployMode",
                    "entInfoSyss_3_deployAddrCounty",
                    "imgId_b",
                    "entInfoSyss_0_deployAddr",
                    "industryCategory",
                    "entInfoSyss_3_deployAddrProvince",
                    "entInfoSyss_2_deployAddrCity",
                    "orgAddrCounty",
                    "entInfoSyss_1_deployMode",
                    "entInfoSyss_2_deployMode",
                    "entInfoSyss_0_sysType",
                    "orgAddrCountyDesc",
                    "entApplyId",
                    "legalCrtType",
                    "entInfoSyss_0_deployAddrCity",
                    "entInfoSyss_1_deployAddrProvince",
                    "entInfoSyss_0_deployMode",
                    "contactName",
                    "orgCrtCode",
                    "entInfoSyss_1_id",
                    "orgAddrProvince",
                    "contactCrtType",
                    "userName",
                ]
            )
        ),
        Step(RunTestCase("更新已审核通过的企业前缀").call(UpdatePrefix)),
        Step(RunTestCase("校验更新后的前缀信息").call(ApplyOrNot4Update)),
    ]


if __name__ == "__main__":
    TestCaseUpdate().test_start()
