# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/entapply/apply_or_not_update_before.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseApplyOrNotUpdateBefore(HttpRunner):

    config = (
        Config("企业注册查询注册信息")
        .base_url("${ENV(HOST)}")
        .verify(False)
        .export(
            *[
                "imgId",
                "imgId_b",
                "imgId_f",
                "applyId",
                "entId",
                "entUserId",
                "prefix",
                "entApplyId",
                "userName",
                "userId",
                "entPrefix",
                "legalEmail",
                "legalPhone",
                "contactCrtNo",
                "contactCrtType",
                "contactEmail",
                "contactName",
                "contactPhone",
                "industryCategory",
                "industrySpecific",
                "orgName",
                "orgNature",
                "orgAddrProvince",
                "orgAddrCity",
                "orgAddrCounty",
                "orgAddr",
                "orgCrtType",
                "orgCrtCode",
                "legalName",
                "legalCrtType",
                "legalCrtNo",
                "legalCrtFrontImgRid",
                "legalCrtBackImgRid",
                "orgCrtImgRid",
                "orgNatureDesc",
                "orgCategorySpecificDesc",
                "orgAddrProvinceDesc",
                "orgAddrCountyDesc",
                "orgAddrCityDesc",
                "legalCrtTypeDesc",
                "createDate",
                "updateDate",
                "entInfoSyss_0_id",
                "entInfoSyss_0_entApplyId",
                "entInfoSyss_0_sysType",
                "entInfoSyss_0_deployMode",
                "entInfoSyss_1_id",
                "entInfoSyss_1_entApplyId",
                "entInfoSyss_1_sysType",
                "entInfoSyss_1_deployMode",
                "entInfoSyss_2_id",
                "entInfoSyss_2_entApplyId",
                "entInfoSyss_2_sysType",
                "entInfoSyss_2_deployMode",
                "entInfoSyss_3_id",
                "entInfoSyss_3_entApplyId",
                "entInfoSyss_3_sysType",
                "entInfoSyss_3_deployMode",
                "entInfoSyss_0_deployAddr",
                "entInfoSyss_0_deployAddrProvince",
                "entInfoSyss_0_deployAddrCity",
                "entInfoSyss_0_deployAddrCounty",
                "entInfoSyss_1_deployAddr",
                "entInfoSyss_1_deployAddrProvince",
                "entInfoSyss_1_deployAddrCity",
                "entInfoSyss_1_deployAddrCounty",
                "entInfoSyss_2_deployAddr",
                "entInfoSyss_2_deployAddrProvince",
                "entInfoSyss_2_deployAddrCity",
                "entInfoSyss_2_deployAddrCounty",
                "entInfoSyss_3_deployAddr",
                "entInfoSyss_3_deployAddrProvince",
                "entInfoSyss_3_deployAddrCity",
                "entInfoSyss_3_deployAddrCounty",
            ]
        )
    )

    teststeps = [
        Step(
            RunRequest("企业注册查询注册信息")
            .get("/api/v3/entApply/applyOrNot")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"SESSION": "$entSession"})
            .extract()
            .with_jmespath("body.data.nbmsEntApplyPO.id", "applyId")
            .with_jmespath("body.data.nbmsEntApplyPO.userId", "userId")
            .with_jmespath("body.data.nbmsEntApplyPO.userName", "userName")
            .with_jmespath("body.data.nbmsEntApplyPO.contactCrtFrontImgRid", "imgId_f")
            .with_jmespath("body.data.nbmsEntApplyPO.contactCrtBackImgRid", "imgId_b")
            .with_jmespath("body.data.nbmsEntPO.id", "entId")
            .with_jmespath("body.data.nbmsEntPO.userId", "entUserId")
            .with_jmespath("body.data.nbmsEntPO.entPrefix", "entPrefix")
            .with_jmespath("body.data.nbmsEntPO.entPrefix", "prefix")
            .with_jmespath("body.data.nbmsEntApplyPO.contactCrtNo", "contactCrtNo")
            .with_jmespath("body.data.nbmsEntApplyPO.contactCrtType", "contactCrtType")
            .with_jmespath("body.data.nbmsEntApplyPO.contactEmail", "contactEmail")
            .with_jmespath("body.data.nbmsEntApplyPO.contactName", "contactName")
            .with_jmespath("body.data.nbmsEntApplyPO.contactPhone", "contactPhone")
            .with_jmespath(
                "body.data.nbmsEntApplyPO.industryCategory", "industryCategory"
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.industrySpecific", "industrySpecific"
            )
            .with_jmespath("body.data.nbmsEntApplyPO.orgName", "orgName")
            .with_jmespath("body.data.nbmsEntApplyPO.orgNature", "orgNature")
            .with_jmespath(
                "body.data.nbmsEntApplyPO.orgAddrProvince", "orgAddrProvince"
            )
            .with_jmespath("body.data.nbmsEntApplyPO.orgAddrCity", "orgAddrCity")
            .with_jmespath("body.data.nbmsEntApplyPO.orgAddrCounty", "orgAddrCounty")
            .with_jmespath("body.data.nbmsEntApplyPO.orgAddr", "orgAddr")
            .with_jmespath("body.data.nbmsEntApplyPO.orgCrtType", "orgCrtType")
            .with_jmespath("body.data.nbmsEntApplyPO.orgCrtCode", "orgCrtCode")
            .with_jmespath("body.data.nbmsEntApplyPO.legalName", "legalName")
            .with_jmespath("body.data.nbmsEntApplyPO.legalEmail", "legalEmail")
            .with_jmespath("body.data.nbmsEntApplyPO.legalPhone", "legalPhone")
            .with_jmespath("body.data.nbmsEntApplyPO.legalCrtType", "legalCrtType")
            .with_jmespath("body.data.nbmsEntApplyPO.legalCrtNo", "legalCrtNo")
            .with_jmespath(
                "body.data.nbmsEntApplyPO.legalCrtFrontImgRid", "legalCrtFrontImgRid"
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.legalCrtBackImgRid", "legalCrtBackImgRid"
            )
            .with_jmespath("body.data.nbmsEntApplyPO.orgCrtImgRid", "orgCrtImgRid")
            .with_jmespath("body.data.nbmsEntApplyPO.orgCrtImgRid", "imgId")
            .with_jmespath("body.data.nbmsEntApplyPO.orgNatureDesc", "orgNatureDesc")
            .with_jmespath(
                "body.data.nbmsEntApplyPO.orgCategorySpecificDesc",
                "orgCategorySpecificDesc",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.orgAddrProvinceDesc", "orgAddrProvinceDesc"
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.orgAddrCountyDesc", "orgAddrCountyDesc"
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.orgAddrCityDesc", "orgAddrCityDesc"
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.legalCrtTypeDesc", "legalCrtTypeDesc"
            )
            .with_jmespath("body.data.nbmsEntApplyPO.createDate", "createDate")
            .with_jmespath("body.data.nbmsEntApplyPO.updateDate", "updateDate")
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[0].id", "entInfoSyss_0_id"
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[0].entApplyId",
                "entInfoSyss_0_entApplyId",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[0].entApplyId", "entApplyId"
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[0].sysType",
                "entInfoSyss_0_sysType",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[0].deployMode",
                "entInfoSyss_0_deployMode",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[0].deployAddr",
                "entInfoSyss_0_deployAddr",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[0].deployAddrProvince",
                "entInfoSyss_0_deployAddrProvince",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[0].deployAddrCity",
                "entInfoSyss_0_deployAddrCity",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[0].deployAddrCounty",
                "entInfoSyss_0_deployAddrCounty",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[1].id", "entInfoSyss_1_id"
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[1].entApplyId",
                "entInfoSyss_1_entApplyId",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[1].sysType",
                "entInfoSyss_1_sysType",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[1].deployMode",
                "entInfoSyss_1_deployMode",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[1].deployAddr",
                "entInfoSyss_1_deployAddr",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[1].deployAddrProvince",
                "entInfoSyss_1_deployAddrProvince",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[1].deployAddrCity",
                "entInfoSyss_1_deployAddrCity",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[1].deployAddrCounty",
                "entInfoSyss_1_deployAddrCounty",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[2].id", "entInfoSyss_2_id"
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[2].entApplyId",
                "entInfoSyss_2_entApplyId",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[2].sysType",
                "entInfoSyss_2_sysType",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[2].deployMode",
                "entInfoSyss_2_deployMode",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[2].deployAddr",
                "entInfoSyss_2_deployAddr",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[2].deployAddrProvince",
                "entInfoSyss_2_deployAddrProvince",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[2].deployAddrCity",
                "entInfoSyss_2_deployAddrCity",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[2].deployAddrCounty",
                "entInfoSyss_2_deployAddrCounty",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[3].id", "entInfoSyss_3_id"
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[3].entApplyId",
                "entInfoSyss_3_entApplyId",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[3].sysType",
                "entInfoSyss_3_sysType",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[3].deployMode",
                "entInfoSyss_3_deployMode",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[3].deployAddr",
                "entInfoSyss_3_deployAddr",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[3].deployAddrProvince",
                "entInfoSyss_3_deployAddrProvince",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[3].deployAddrCity",
                "entInfoSyss_3_deployAddrCity",
            )
            .with_jmespath(
                "body.data.nbmsEntApplyPO.entInfoSyss[3].deployAddrCounty",
                "entInfoSyss_3_deployAddrCounty",
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.message", "success")
        ),
    ]


if __name__ == "__main__":
    TestCaseApplyOrNotUpdateBefore().test_start()
