# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/entapply/apply_or_not_4_update.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseApplyOrNot4Update(HttpRunner):

    config = Config("校验更新后的前缀信息").base_url("${ENV(HOST)}").verify(False)

    teststeps = [
        Step(
            RunRequest("校验更新后的前缀信息")
            .get("/api/v3/entApply/applyOrNot")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"SESSION": "$entSession"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.message", "success")
            .assert_equal("body.data.nbmsEntApplyPO.legalName", "$legalNameUpdate")
        ),
    ]


if __name__ == "__main__":
    TestCaseApplyOrNot4Update().test_start()
