# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/applyRecord/entApplyRecordPage-ent.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseEntapplyrecordpageEnt(HttpRunner):

    config = (
        Config("申请记录分页列表")
        .variables(
            **{
                "currentPage": 1,
                "order": "",
                "orderProp": "",
                "orgName": "",
                "rangeTime": "",
            }
        )
        .base_url("${ENV(HOST)}")
        .verify(False)
        .export(*["applyId"])
    )

    teststeps = [
        Step(
            RunRequest("申请记录分页列表")
            .get("/api/v3/entApply/record/pageQuery")
            .with_params(
                **{
                    "currentPage": "",
                    "order": "",
                    "orderProp": "",
                    "orgName": "$orgName",
                    "rangeTime": "",
                }
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"SESSION": "$entSession"})
            .extract()
            .with_jmespath("body.data.content[0].id", "applyId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.message", "success")
            .assert_equal("body.status", 1)
        ),
    ]


if __name__ == "__main__":
    TestCaseEntapplyrecordpageEnt().test_start()
