# NOTE: Generated By HttpRunner v3.1.6
# FROM: testsuites/uploadfile/test_upload_xml.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.login.login_ent_test import TestCaseLoginEnt as LoginEnt

from testcases.uploadfile.UploadXml_test import TestCaseUploadxml as Uploadxml


class TestCaseTestUploadXml(HttpRunner):

    config = Config("xml上传").variables(
        **{
            "entaccount": "${ENV(entaccount)}",
            "entpassword": "${ENV(entpassword)}",
            "fileName": "${ENV(xmlFileName)}",
        }
    )

    teststeps = [
        Step(RunTestCase("登录-企业").call(LoginEnt).export(*["entSession"])),
        Step(RunTestCase("上传xml文件").call(Uploadxml)),
    ]


if __name__ == "__main__":
    TestCaseTestUploadXml().test_start()
