# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/prefixAudit/audit/v3-ent-audit-save-cancel.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseV3EntAuditSaveCancel(HttpRunner):

    config = Config("企业审核保存").base_url("${ENV(HOST)}").verify(False)

    teststeps = [
        Step(
            RunRequest("企业审核驳回")
            .post("/api/v3/ent/audit/save")
            .with_params(
                **{
                    "annualFeeRuleId": "$annualFeeRuleId",
                    "applyId": "$applyId",
                    "auditMsg": "提交的资质信息有误，驳回申请",
                    "auditResult": "fail",
                    "entPrefix": "$prefix",
                    "regFeeRuleId": "$regFeeRuleId",
                }
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.56",
                }
            )
            .with_cookies(**{"SESSION": "${get_session($username, $password)}"})
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.message", "success")
            .assert_equal("body.status", 1)
            .assert_equal("body.data", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseV3EntAuditSaveCancel().test_start()
