# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/checkhandle/checkId_format.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseCheckidFormat(HttpRunner):

    config = (
        Config("门户查询标识信息格式错误")
        .variables(**{"prefix": "sdfsdfsdf"})
        .base_url("${ENV(HOST)}")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("门户查询标识信息格式错误")
            .get("/api/identityv2/query/data")
            .with_params(**{"handle": "$prefix"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.message", "标识格式不合法")
        ),
    ]


if __name__ == "__main__":
    TestCaseCheckidFormat().test_start()
