# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/entBussinessInfo/entBusinessInfoDel.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseEntbusinessinfodel(HttpRunner):

    config = (
        Config("标识业务数据删除")
        .variables(**{"id": "$entBusinessId"})
        .base_url("${ENV(HOST)}")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("标识业务数据删除")
            .post("/api/v3/entBussInfo")
            .with_params(**{"id": "$id"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                    "X-HTTP-Method-Override": "delete",
                }
            )
            .with_cookies(**{"SESSION": "$entSession"})
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.message", "success")
            .assert_equal("body.status", 1)
            .assert_equal("body.data", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseEntbusinessinfodel().test_start()
