config:
    name: 保存前缀配置
    base_url: ${ENV(HOST)}
    verify: false
teststeps:
-   name: 保存前缀配置
    request:
        cookies:
            SESSION: $adminSession
        headers:
            Accept: application/json, text/plain, */*
            Accept-Encoding: gzip, deflate
            Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
            Connection: keep-alive
            Content-Type: application/json
            User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
                (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.56
        json:
            entNameCn: $entNameCnPage
            entPrefix: $entPrefixPage
            ip: $ip
            ipType: $ipType
            objName: $entNameCnPage
            prefixId: $prefixIdPage
            tcpPort: $tcpPort
            userId: $userIdPage
            httpPort: $httpPort
            udpPort: $udpPort
        method: POST
        url: /api/v3/ent/prefix/manage/saveConfig
    validate:
    -   eq:
        - status_code
        - 200
    -   eq:
        - body.message
        - success
    -   eq:
        - body.status
        - 1
    -   eq:
        - body.data
        - true
