# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/prefixmanager/ent-prefix-proxy-audit.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseEntPrefixProxyAudit(HttpRunner):

    config = (
        Config("前缀审核列表")
        .base_url("${ENV(HOST)}")
        .verify(False)
        .export(*["prefixauditid"])
    )

    teststeps = [
        Step(
            RunRequest("前缀审核列表")
            .get("/api/proxyserver/prefix/audit/pageQuery")
            .with_params(
                **{
                    "cache": "1663920502544",
                    "currentPage": "1",
                    "entNameCn": "",
                    "escrowOrgName": "",
                    "order": "",
                    "orderProp": "",
                    "prefix": "$pendingPrefixCondition",
                }
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"SESSION": "$adminSession"})
            .extract()
            .with_jmespath("body.data.content[0].id", "prefixauditid")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.message", "success")
            .assert_equal("body.status", 1)
        ),
    ]


if __name__ == "__main__":
    TestCaseEntPrefixProxyAudit().test_start()
