# NOTE: Generated By HttpRunner v3.1.6
# FROM: testsuites/homepage/ent_register.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.login.login_admin_test import TestCaseLoginAdmin as LoginAdmin

from testcases.statistics.indexstatistics_test import (
    TestCaseIndexstatistics as Indexstatistics,
)

from testsuites.prefixAudit.prefixAudit_test import TestCasePrefixaudit as Prefixaudit

from testcases.statistics.indexstatistics_check_registerNum_test import (
    TestCaseIndexstatisticsCheckRegisternum as IndexstatisticsCheckRegisternum,
)


class TestCaseEntRegister(HttpRunner):

    config = (
        Config("首页-数据汇总-企业数量")
        .variables(
            **{"account": "${ENV(adminaccount)}", "password": "${ENV(adminpassword)}"}
        )
        .export(*["applyNum", "prefixNum", "entNum"])
    )

    teststeps = [
        Step(RunTestCase("登录-管理员").call(LoginAdmin).export(*["adminSession"])),
        Step(
            RunTestCase("企业申请中统计")
            .call(Indexstatistics)
            .export(
                *[
                    "entNum",
                    "resolvnum",
                    "identityNum",
                    "delnum",
                    "prefixNum",
                    "applyNum",
                ]
            )
        ),
        Step(RunTestCase("前缀注册并审核通过").call(Prefixaudit).export(*["entPrefix"])),
        Step(RunTestCase("登录-管理员").call(LoginAdmin).export(*["adminSession"])),
        Step(RunTestCase("企业数量统计").call(IndexstatisticsCheckRegisternum)),
    ]


if __name__ == "__main__":
    TestCaseEntRegister().test_start()
