# NOTE: Generated By HttpRunner v3.1.6
# FROM: testsuites/homepage/ent_applying.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.login.login_admin_test import TestCaseLoginAdmin as LoginAdmin

from testcases.statistics.indexstatistics_test import (
    TestCaseIndexstatistics as Indexstatistics,
)

from testsuites.prefixAudit.prefix_register_test import (
    TestCasePrefixRegister as PrefixRegister,
)

from testcases.statistics.indexstatistics_check_applyNum_test import (
    TestCaseIndexstatisticsCheckApplynum as IndexstatisticsCheckApplynum,
)


class TestCaseEntApplying(HttpRunner):

    config = (
        Config("首页-数据汇总-企业申请中")
        .variables(
            **{"account": "${ENV(adminaccount)}", "password": "${ENV(adminpassword)}"}
        )
        .export(*["applyNum", "prefixNum", "entNum"])
    )

    teststeps = [
        Step(RunTestCase("登录-管理员").call(LoginAdmin).export(*["adminSession"])),
        Step(
            RunTestCase("企业申请中统计")
            .call(Indexstatistics)
            .export(
                *[
                    "entNum",
                    "identityNum",
                    "applyNum",
                    "delnum",
                    "resolvnum",
                    "prefixNum",
                ]
            )
        ),
        Step(RunTestCase("前缀注册").call(PrefixRegister)),
        Step(RunTestCase("登录-管理员").call(LoginAdmin).export(*["adminSession"])),
        Step(RunTestCase("企业申请中统计").call(IndexstatisticsCheckApplynum)),
    ]


if __name__ == "__main__":
    TestCaseEntApplying().test_start()
