# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/logmanager/verficationlog.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseVerficationlog(HttpRunner):

    config = Config("核验日志列表").base_url("${ENV(HOST)}").verify(False)

    teststeps = [
        Step(
            RunRequest("核验日志列表")
            .get("/api/log/snms/verification")
            .with_params(
                **{
                    "currentPage": "1",
                    "order": "",
                    "orderProp": "",
                    "rangeTime": "",
                    "serviceName": "",
                    "serviceStatus": "",
                }
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"SESSION": "$adminSession"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.message", "success")
            .assert_equal("body.data.content[0].verifyContent", "法人资格")
        ),
    ]


if __name__ == "__main__":
    TestCaseVerficationlog().test_start()
