# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/prefixAudit/register.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseRegister(HttpRunner):

    config = Config("用户注册").base_url("${ENV(HOST)}").verify(False)

    teststeps = [
        Step(
            RunRequest("用户注册")
            .post("/api/home/test/registry")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36",
                }
            )
            .with_json(
                {
                    "email": "$email",
                    "mobile": "$mobile",
                    "openId": "",
                    "openUserName": "",
                    "password": "$entpassword",
                    "remarks": "",
                    "username": "$entaccount",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.message", "success")
            .assert_equal("body.status", 1)
            .assert_contains("body.message", "success")
            .assert_contained_by("body.status", [1, 200])
        ),
    ]


if __name__ == "__main__":
    TestCaseRegister().test_start()
