# NOTE: Generated By HttpRunner v3.1.6
# FROM: testsuites/checkFlow/check_prefix_success.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.prefixAudit.register_test import TestCaseRegister as Register

from testcases.login.login_ent_test import TestCaseLoginEnt as LoginEnt

from testcases.prefixAudit.register.upload_img_test import (
    TestCaseUploadImg as UploadImg,
)

from testcases.prefixAudit.register.upload_img_f_test import (
    TestCaseUploadImgF as UploadImgF,
)

from testcases.prefixAudit.register.upload_img_b_test import (
    TestCaseUploadImgB as UploadImgB,
)

from testcases.prefixAudit.register.submit_first_test import (
    TestCaseSubmitFirst as SubmitFirst,
)

from testcases.prefixAudit.register.apply_or_not_test import (
    TestCaseApplyOrNot as ApplyOrNot,
)

from testcases.prefixAudit.register.submit_second_test import (
    TestCaseSubmitSecond as SubmitSecond,
)

from testcases.prefixAudit.register.submit_final_test import (
    TestCaseSubmitFinal as SubmitFinal,
)

from testcases.login.login_admin_test import TestCaseLoginAdmin as LoginAdmin

from testcases.prefixAudit.audit.finance_rule_findRule_reg_test import (
    TestCaseFinanceRuleFindruleReg as FinanceRuleFindruleReg,
)

from testcases.prefixAudit.audit.finance_rule_findRule_test import (
    TestCaseFinanceRuleFindrule as FinanceRuleFindrule,
)

from testcases.prefixmanager.ent_prefix_manage_pageQuery_base_test import (
    TestCaseEntPrefixManagePagequeryBase as EntPrefixManagePagequeryBase,
)

from testcases.prefixAudit.audit.v3_ent_audit_save_cancel_test import (
    TestCaseV3EntAuditSaveCancel as V3EntAuditSaveCancel,
)

from testcases.prefixAudit.register.apply_or_not_refuse_test import (
    TestCaseApplyOrNotRefuse as ApplyOrNotRefuse,
)


class TestCaseCheckPrefixSuccess(HttpRunner):

    config = (
        Config("企业审核驳回接口")
        .variables(
            **{
                "email": "${get_email()}",
                "mobile": "${get_mobile()}",
                "username": "${get_username()}",
                "account": "${ENV(adminaccount)}",
                "password": "${ENV(adminpassword)}",
                "entaccount": "$username",
                "entpassword": "${ENV(entpassword)}",
                "prefix": "${ENV(prefix_second)}${get_random_param(1,10000000000,1)}",
                "personId": "${get_idcardno()}",
            }
        )
        .base_url("${ENV(HOST)}")
        .verify(False)
    )

    teststeps = [
        Step(RunTestCase("用户注册").call(Register)),
        Step(RunTestCase("登录-企业").call(LoginEnt).export(*["entSession"])),
        Step(RunTestCase("前缀注册企业资质图片上传").call(UploadImg).export(*["imgId"])),
        Step(RunTestCase("前缀注册企业联系人身份证图片正面上传").call(UploadImgF).export(*["imgId_f"])),
        Step(RunTestCase("前缀注册企业联系人身份证图片背面上传").call(UploadImgB).export(*["imgId_b"])),
        Step(RunTestCase("企业注册第一步提交信息").call(SubmitFirst)),
        Step(
            RunTestCase("企业注册查询注册信息")
            .call(ApplyOrNot)
            .export(
                *[
                    "orgName",
                    "orgAddrCity",
                    "entInfoSyss_3_deployAddrCounty",
                    "entInfoSyss_0_entApplyId",
                    "legalCrtTypeDesc",
                    "entInfoSyss_0_deployAddrCity",
                    "orgCrtImgRid",
                    "industrySpecific",
                    "entInfoSyss_3_id",
                    "legalCrtFrontImgRid",
                    "entInfoSyss_2_deployAddrProvince",
                    "orgNature",
                    "legalCrtNo",
                    "orgNatureDesc",
                    "orgCategorySpecificDesc",
                    "entInfoSyss_3_deployAddr",
                    "contactEmail",
                    "updateDate",
                    "entInfoSyss_0_deployAddrProvince",
                    "entId",
                    "orgCrtType",
                    "entInfoSyss_1_deployMode",
                    "entInfoSyss_2_id",
                    "orgAddr",
                    "entInfoSyss_2_entApplyId",
                    "legalEmail",
                    "entInfoSyss_3_entApplyId",
                    "entInfoSyss_3_sysType",
                    "legalCrtBackImgRid",
                    "prefix",
                    "legalCrtType",
                    "entInfoSyss_2_deployAddrCity",
                    "entInfoSyss_1_entApplyId",
                    "entInfoSyss_1_deployAddrProvince",
                    "entInfoSyss_0_id",
                    "entInfoSyss_2_deployAddrCounty",
                    "contactName",
                    "orgAddrCityDesc",
                    "imgId_b",
                    "legalName",
                    "entApplyId",
                    "orgAddrCountyDesc",
                    "entInfoSyss_2_deployAddr",
                    "createDate",
                    "userName",
                    "industryCategory",
                    "entInfoSyss_0_deployMode",
                    "entInfoSyss_3_deployMode",
                    "imgId_f",
                    "entInfoSyss_0_deployAddrCounty",
                    "orgCrtCode",
                    "entInfoSyss_2_deployMode",
                    "applyId",
                    "entInfoSyss_1_deployAddr",
                    "entInfoSyss_1_deployAddrCity",
                    "imgId",
                    "entInfoSyss_1_deployAddrCounty",
                    "entInfoSyss_3_deployAddrProvince",
                    "entInfoSyss_3_deployAddrCity",
                    "entUserId",
                    "entInfoSyss_2_sysType",
                    "entInfoSyss_0_sysType",
                    "contactCrtType",
                    "contactCrtNo",
                    "entInfoSyss_1_id",
                    "entInfoSyss_0_deployAddr",
                    "legalPhone",
                    "contactPhone",
                    "entInfoSyss_1_sysType",
                    "userId",
                    "orgAddrCounty",
                    "orgAddrProvinceDesc",
                    "orgAddrProvince",
                ]
            )
        ),
        Step(RunTestCase("企业注册第二步提交信息").call(SubmitSecond)),
        Step(
            RunTestCase("企业注册查询注册信息")
            .call(ApplyOrNot)
            .export(
                *[
                    "orgName",
                    "orgAddrCity",
                    "entInfoSyss_3_deployAddrCounty",
                    "entInfoSyss_0_entApplyId",
                    "legalCrtTypeDesc",
                    "entInfoSyss_0_deployAddrCity",
                    "orgCrtImgRid",
                    "industrySpecific",
                    "entInfoSyss_3_id",
                    "legalCrtFrontImgRid",
                    "entInfoSyss_2_deployAddrProvince",
                    "orgNature",
                    "legalCrtNo",
                    "orgNatureDesc",
                    "orgCategorySpecificDesc",
                    "entInfoSyss_3_deployAddr",
                    "contactEmail",
                    "updateDate",
                    "entInfoSyss_0_deployAddrProvince",
                    "entId",
                    "orgCrtType",
                    "entInfoSyss_1_deployMode",
                    "entInfoSyss_2_id",
                    "orgAddr",
                    "entInfoSyss_2_entApplyId",
                    "legalEmail",
                    "entInfoSyss_3_entApplyId",
                    "entInfoSyss_3_sysType",
                    "legalCrtBackImgRid",
                    "prefix",
                    "legalCrtType",
                    "entInfoSyss_2_deployAddrCity",
                    "entInfoSyss_1_entApplyId",
                    "entInfoSyss_1_deployAddrProvince",
                    "entInfoSyss_0_id",
                    "entInfoSyss_2_deployAddrCounty",
                    "contactName",
                    "orgAddrCityDesc",
                    "imgId_b",
                    "legalName",
                    "entApplyId",
                    "orgAddrCountyDesc",
                    "entInfoSyss_2_deployAddr",
                    "createDate",
                    "userName",
                    "industryCategory",
                    "entInfoSyss_0_deployMode",
                    "entInfoSyss_3_deployMode",
                    "imgId_f",
                    "entInfoSyss_0_deployAddrCounty",
                    "orgCrtCode",
                    "entInfoSyss_2_deployMode",
                    "applyId",
                    "entInfoSyss_1_deployAddr",
                    "entInfoSyss_1_deployAddrCity",
                    "imgId",
                    "entInfoSyss_1_deployAddrCounty",
                    "entInfoSyss_3_deployAddrProvince",
                    "entInfoSyss_3_deployAddrCity",
                    "entUserId",
                    "entInfoSyss_2_sysType",
                    "entInfoSyss_0_sysType",
                    "contactCrtType",
                    "contactCrtNo",
                    "entInfoSyss_1_id",
                    "entInfoSyss_0_deployAddr",
                    "legalPhone",
                    "contactPhone",
                    "entInfoSyss_1_sysType",
                    "userId",
                    "orgAddrCounty",
                    "orgAddrProvinceDesc",
                    "orgAddrProvince",
                ]
            )
        ),
        Step(RunTestCase("企业注册最终第三步提交信息").call(SubmitFinal)),
        Step(RunTestCase("登录-管理员").call(LoginAdmin).export(*["adminSession"])),
        Step(RunTestCase("注册费").call(FinanceRuleFindruleReg).export(*["regFeeRuleId"])),
        Step(RunTestCase("年费").call(FinanceRuleFindrule).export(*["annualFeeRuleId"])),
        Step(
            RunTestCase("前缀管理分页")
            .call(EntPrefixManagePagequeryBase)
            .export(
                *[
                    "prefixIdPage",
                    "entPrefixPage",
                    "userIdPage",
                    "proxyStatePage",
                    "entNameCnPage",
                ]
            )
        ),
        Step(RunTestCase("企业审核驳回").call(V3EntAuditSaveCancel)),
        Step(RunTestCase("登录-企业").call(LoginEnt).export(*["entSession"])),
        Step(RunTestCase("企业查看申请状态").call(ApplyOrNotRefuse)),
    ]


if __name__ == "__main__":
    TestCaseCheckPrefixSuccess().test_start()
