# NOTE: Generated By HttpRunner v3.1.6
# FROM: testsuites/prefixAlloc/prefixAlloc-10.yaml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.prefixAudit.register_test import TestCaseRegister as Register

from testcases.login.login_ent_test import TestCaseLoginEnt as LoginEnt

from testcases.prefixAudit.register.upload_img_test import (
    TestCaseUploadImg as UploadImg,
)

from testcases.prefixAudit.register.upload_img_f_test import (
    TestCaseUploadImgF as UploadImgF,
)

from testcases.prefixAudit.register.upload_img_b_test import (
    TestCaseUploadImgB as UploadImgB,
)

from testcases.prefixAudit.register.submit_first_test import (
    TestCaseSubmitFirst as SubmitFirst,
)

from testcases.prefixAudit.register.apply_or_not_test import (
    TestCaseApplyOrNot as ApplyOrNot,
)

from testcases.prefixAudit.register.submit_second_test import (
    TestCaseSubmitSecond as SubmitSecond,
)

from testcases.prefixAudit.register.submit_final_test import (
    TestCaseSubmitFinal as SubmitFinal,
)

from testcases.login.login_admin_test import TestCaseLoginAdmin as LoginAdmin

from testcases.prefixAudit.audit.finance_rule_findRule_test import (
    TestCaseFinanceRuleFindrule as FinanceRuleFindrule,
)

from testcases.prefixAudit.audit.finance_rule_findRule_reg_test import (
    TestCaseFinanceRuleFindruleReg as FinanceRuleFindruleReg,
)

from testcases.prefixAudit.audit.v3_ent_audit_save_test import (
    TestCaseV3EntAuditSave as V3EntAuditSave,
)

from testcases.prefixAlloc.ent_prefix_alloc_pageQuery_test import (
    TestCaseEntPrefixAllocPagequery as EntPrefixAllocPagequery,
)

from testcases.prefixmanager.ent_finance_rule_findRule_reg_test import (
    TestCaseEntFinanceRuleFindruleReg as EntFinanceRuleFindruleReg,
)

from testcases.prefixmanager.ent_finance_rule_findRule_annual_test import (
    TestCaseEntFinanceRuleFindruleAnnual as EntFinanceRuleFindruleAnnual,
)

from testcases.prefixAlloc.ent_prefix_alloc_savePrefix_test import (
    TestCaseEntPrefixAllocSaveprefix as EntPrefixAllocSaveprefix,
)

from testcases.prefixAlloc.ent_prefix_alloc_savePrefix_2_test import (
    TestCaseEntPrefixAllocSaveprefix2 as EntPrefixAllocSaveprefix2,
)

from testcases.prefixAlloc.ent_prefix_manage_delete_2_test import (
    TestCaseEntPrefixManageDelete2 as EntPrefixManageDelete2,
)

from testcases.prefixAlloc.ent_prefix_alloc_pageQuery_2_test import (
    TestCaseEntPrefixAllocPagequery2 as EntPrefixAllocPagequery2,
)


class TestCasePrefixalloc10(HttpRunner):

    config = Config("前缀分配删除校验").variables(
        **{
            "email": "${get_email()}",
            "mobile": "${get_mobile()}",
            "username": "${get_username()}",
            "account": "${ENV(adminaccount)}",
            "password": "${ENV(adminpassword)}",
            "entaccount": "$username",
            "entpassword": "${ENV(entpassword)}",
            "moneyType1": 1,
            "moneyType2": 2,
            "pendingPrefixCondition": "${ENV(prefix_second)}${get_random_param(1000,10000000000,1)}",
            "pendingPrefixConditionSecond": "${ENV(prefix_second)}${get_random_param(1000,10000000000,1)}",
            "delTemplateAll": 1,
            "transferPrefix": "",
            "prefix": "${ENV(prefix_second)}${get_random_param(1000,10000000000,1)}",
            "personId": "${get_idcardno()}",
        }
    )

    teststeps = [
        Step(RunTestCase("用户注册").call(Register)),
        Step(RunTestCase("登录-企业").call(LoginEnt).export(*["entSession"])),
        Step(RunTestCase("前缀注册企业资质图片上传").call(UploadImg).export(*["imgId"])),
        Step(RunTestCase("前缀注册企业联系人身份证图片正面上传").call(UploadImgF).export(*["imgId_f"])),
        Step(RunTestCase("前缀注册企业联系人身份证图片背面上传").call(UploadImgB).export(*["imgId_b"])),
        Step(RunTestCase("企业注册第一步提交信息").call(SubmitFirst)),
        Step(
            RunTestCase("企业注册查询注册信息")
            .call(ApplyOrNot)
            .export(
                *[
                    "orgAddrCity",
                    "entInfoSyss_0_deployAddr",
                    "orgCrtImgRid",
                    "orgAddrCountyDesc",
                    "legalCrtNo",
                    "entInfoSyss_3_deployAddrCounty",
                    "imgId",
                    "orgNature",
                    "entInfoSyss_3_sysType",
                    "legalName",
                    "contactEmail",
                    "orgAddrCounty",
                    "userId",
                    "orgName",
                    "legalCrtFrontImgRid",
                    "entInfoSyss_2_deployAddrCity",
                    "entInfoSyss_3_deployAddrProvince",
                    "entInfoSyss_0_deployAddrProvince",
                    "entInfoSyss_2_deployAddrCounty",
                    "entApplyId",
                    "legalCrtBackImgRid",
                    "entInfoSyss_2_deployAddrProvince",
                    "updateDate",
                    "orgCrtCode",
                    "orgAddrCityDesc",
                    "entInfoSyss_0_deployAddrCity",
                    "legalPhone",
                    "entInfoSyss_2_entApplyId",
                    "prefix",
                    "entId",
                    "entInfoSyss_1_deployAddrCounty",
                    "applyId",
                    "contactCrtNo",
                    "orgAddrProvinceDesc",
                    "legalEmail",
                    "entInfoSyss_1_id",
                    "entInfoSyss_1_deployAddrCity",
                    "contactCrtType",
                    "orgAddr",
                    "entInfoSyss_3_deployAddr",
                    "entInfoSyss_2_sysType",
                    "imgId_b",
                    "entInfoSyss_1_sysType",
                    "orgAddrProvince",
                    "entInfoSyss_2_deployAddr",
                    "entInfoSyss_0_sysType",
                    "entInfoSyss_3_id",
                    "entInfoSyss_0_id",
                    "legalCrtTypeDesc",
                    "orgNatureDesc",
                    "entInfoSyss_1_deployAddrProvince",
                    "entInfoSyss_2_id",
                    "entInfoSyss_1_deployAddr",
                    "industryCategory",
                    "createDate",
                    "contactPhone",
                    "userName",
                    "orgCrtType",
                    "legalCrtType",
                    "entInfoSyss_2_deployMode",
                    "entInfoSyss_3_entApplyId",
                    "entInfoSyss_3_deployMode",
                    "imgId_f",
                    "entInfoSyss_0_deployAddrCounty",
                    "entInfoSyss_0_entApplyId",
                    "industrySpecific",
                    "entInfoSyss_1_entApplyId",
                    "contactName",
                    "entInfoSyss_0_deployMode",
                    "entInfoSyss_1_deployMode",
                    "orgCategorySpecificDesc",
                    "entUserId",
                    "entInfoSyss_3_deployAddrCity",
                ]
            )
        ),
        Step(RunTestCase("企业注册第二步提交信息").call(SubmitSecond)),
        Step(
            RunTestCase("企业注册查询注册信息")
            .call(ApplyOrNot)
            .export(
                *[
                    "orgAddrCity",
                    "entInfoSyss_0_deployAddr",
                    "orgCrtImgRid",
                    "orgAddrCountyDesc",
                    "legalCrtNo",
                    "entInfoSyss_3_deployAddrCounty",
                    "imgId",
                    "orgNature",
                    "entInfoSyss_3_sysType",
                    "legalName",
                    "contactEmail",
                    "orgAddrCounty",
                    "userId",
                    "orgName",
                    "legalCrtFrontImgRid",
                    "entInfoSyss_2_deployAddrCity",
                    "entInfoSyss_3_deployAddrProvince",
                    "entInfoSyss_0_deployAddrProvince",
                    "entInfoSyss_2_deployAddrCounty",
                    "entApplyId",
                    "legalCrtBackImgRid",
                    "entInfoSyss_2_deployAddrProvince",
                    "updateDate",
                    "orgCrtCode",
                    "orgAddrCityDesc",
                    "entInfoSyss_0_deployAddrCity",
                    "legalPhone",
                    "entInfoSyss_2_entApplyId",
                    "prefix",
                    "entId",
                    "entInfoSyss_1_deployAddrCounty",
                    "applyId",
                    "contactCrtNo",
                    "orgAddrProvinceDesc",
                    "legalEmail",
                    "entInfoSyss_1_id",
                    "entInfoSyss_1_deployAddrCity",
                    "contactCrtType",
                    "orgAddr",
                    "entInfoSyss_3_deployAddr",
                    "entInfoSyss_2_sysType",
                    "imgId_b",
                    "entInfoSyss_1_sysType",
                    "orgAddrProvince",
                    "entInfoSyss_2_deployAddr",
                    "entInfoSyss_0_sysType",
                    "entInfoSyss_3_id",
                    "entInfoSyss_0_id",
                    "legalCrtTypeDesc",
                    "orgNatureDesc",
                    "entInfoSyss_1_deployAddrProvince",
                    "entInfoSyss_2_id",
                    "entInfoSyss_1_deployAddr",
                    "industryCategory",
                    "createDate",
                    "contactPhone",
                    "userName",
                    "orgCrtType",
                    "legalCrtType",
                    "entInfoSyss_2_deployMode",
                    "entInfoSyss_3_entApplyId",
                    "entInfoSyss_3_deployMode",
                    "imgId_f",
                    "entInfoSyss_0_deployAddrCounty",
                    "entInfoSyss_0_entApplyId",
                    "industrySpecific",
                    "entInfoSyss_1_entApplyId",
                    "contactName",
                    "entInfoSyss_0_deployMode",
                    "entInfoSyss_1_deployMode",
                    "orgCategorySpecificDesc",
                    "entUserId",
                    "entInfoSyss_3_deployAddrCity",
                ]
            )
        ),
        Step(RunTestCase("企业注册最终第三步提交信息").call(SubmitFinal)),
        Step(RunTestCase("登录-管理员").call(LoginAdmin).export(*["adminSession"])),
        Step(
            RunTestCase("年费费用查询").call(FinanceRuleFindrule).export(*["annualFeeRuleId"])
        ),
        Step(
            RunTestCase("注册费费用查询")
            .call(FinanceRuleFindruleReg)
            .export(*["regFeeRuleId"])
        ),
        Step(RunTestCase("审核结果保存").call(V3EntAuditSave)),
        Step(
            RunTestCase("前缀分配列表")
            .call(EntPrefixAllocPagequery)
            .export(*["userId", "orgName"])
        ),
        Step(
            RunTestCase("收费标准查询-注册费")
            .call(EntFinanceRuleFindruleReg)
            .export(*["regFeeRuleId"])
        ),
        Step(
            RunTestCase("收费标准查询-年费")
            .call(EntFinanceRuleFindruleAnnual)
            .export(*["annualFeeRuleId"])
        ),
        Step(RunTestCase("保存分配前缀").call(EntPrefixAllocSaveprefix)),
        Step(
            RunTestCase("前缀分配列表")
            .call(EntPrefixAllocPagequery)
            .export(*["userId", "orgName"])
        ),
        Step(
            RunTestCase("收费标准查询-注册费")
            .call(EntFinanceRuleFindruleReg)
            .export(*["regFeeRuleId"])
        ),
        Step(
            RunTestCase("收费标准查询-年费")
            .call(EntFinanceRuleFindruleAnnual)
            .export(*["annualFeeRuleId"])
        ),
        Step(RunTestCase("再次保存分配前缀").call(EntPrefixAllocSaveprefix2)),
        Step(RunTestCase("前缀删除").call(EntPrefixManageDelete2)),
        Step(
            RunTestCase("前缀分配列表")
            .call(EntPrefixAllocPagequery2)
            .export(*["userId", "orgName"])
        ),
    ]


if __name__ == "__main__":
    TestCasePrefixalloc10().test_start()
