# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/statistics/ent_indexstatistics.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseEntIndexstatistics(HttpRunner):

    config = (
        Config("首页-数据汇总-企业用户")
        .base_url("${ENV(HOST)}")
        .verify(False)
        .export(
            *[
                "delnum",
                "identityNum",
                "resolvnum",
                "todayResolvNum",
                "todayIdentityNum",
            ]
        )
    )

    teststeps = [
        Step(
            RunRequest("首页-数据汇总-企业用户")
            .get("/api/index/statistics")
            .with_params(**{"cache": "1663755717060"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"SESSION": "$entSession"})
            .extract()
            .with_jmespath("body.data.delnum", "delnum")
            .with_jmespath("body.data.identityNum", "identityNum")
            .with_jmespath("body.data.resolvnum", "resolvnum")
            .with_jmespath("body.data.todayIdentityNum", "todayIdentityNum")
            .with_jmespath("body.data.todayResolvNum", "todayResolvNum")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.message", "success")
            .assert_equal("body.status", 1)
        ),
    ]


if __name__ == "__main__":
    TestCaseEntIndexstatistics().test_start()
