# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/statistics/handleStathandleRegAnaStat-2.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseHandlestathandlereganastat2(HttpRunner):

    config = (
        Config("前缀注册量，解析量统计")
        .variables(**{"currentPage": "1", "opCode": "1", "order": "", "orderProp": ""})
        .base_url("${ENV(HOST)}")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("注册量，解析量统计")
            .setup_hook("${setup_hook_example()}")
            .get("/api/handleStat/handleRegAnaStat")
            .with_params(
                **{
                    "currentPage": "$currentPage",
                    "opCode": "$opCode",
                    "order": "$order",
                    "orderProp": "$orderProp",
                }
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"SESSION": "$adminSession"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.message", "success")
            .assert_equal("body.status", 1)
            .assert_equal(
                "body.data.tableData.content[?prefix=='$prefix'].prefix", ["$prefix"]
            )
            .assert_equal(
                "body.data.tableData.content[?prefix=='$prefix'].queryNum", [1]
            )
            .assert_equal(
                "body.data.tableData.content[?prefix=='$prefix'].createNum", [1]
            )
        ),
    ]


if __name__ == "__main__":
    TestCaseHandlestathandlereganastat2().test_start()
