# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/statistics/indexstatistics_check_identityNum_stockNum.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseIndexstatisticsCheckIdentitynumStocknum(HttpRunner):

    config = (
        Config("首页-数据汇总-标识注册量及存量")
        .variables(**{"identityNum:$identityNum": None})
        .base_url("${ENV(HOST)}")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("首页-数据汇总-企业申请中")
            .setup_hook("${setup_hook_example()}")
            .get("/api/index/statistics")
            .with_params(**{"cache": "1663755717060"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"SESSION": "$adminSession"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.message", "success")
            .assert_equal("body.status", 1)
            .assert_equal("body.data.identityNum", "${str_to_int4($identityNum)}")
        ),
    ]


if __name__ == "__main__":
    TestCaseIndexstatisticsCheckIdentitynumStocknum().test_start()
