# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/prefixAudit/register/apply_or_not_refuse.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseApplyOrNotRefuse(HttpRunner):

    config = Config("查询企业注册申请为已驳回").base_url("${ENV(HOST)}").verify(False)

    teststeps = [
        Step(
            RunRequest("企业注册查询注册信息")
            .get("/api/v3/entApply/applyOrNot")
            .with_params(**{"isSensetive": "1"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"SESSION": "$entSession"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.message", "success")
            .assert_equal("body.data.nbmsEntApplyPO.firstAuditStatus", 3)
            .assert_equal("body.data.nbmsEntApplyPO.firstAuditMsg", "提交的资质信息有误，驳回申请")
        ),
    ]


if __name__ == "__main__":
    TestCaseApplyOrNotRefuse().test_start()
