# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/prefixAudit/register/upload_img.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseUploadImg(HttpRunner):

    config = (
        Config("前缀注册图片上传")
        .variables(**{"fileName": "${ENV(imgFileName)}"})
        .base_url("${ENV(HOST)}")
        .verify(False)
        .export(*["imgId"])
    )

    teststeps = [
        Step(
            RunRequest("前缀注册企业资质图片上传")
            .post("/api/file/img/upload")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Type": "multipart/form-data; boundary=----WebKitFormBoundaryMniLgY2y7IIAhTZ1",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"SESSION": "$entSession"})
            .upload(**{"file": "upload/$fileName"})
            .extract()
            .with_jmespath("body.data.id", "imgId")
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseUploadImg().test_start()
