# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/uploadfile/UploadXml.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseUploadxml(HttpRunner):

    config = Config("xml上传注册标识").base_url("${ENV(HOST)}").verify(False)

    teststeps = [
        Step(
            RunRequest("xml上传注册标识")
            .post("/api/snms/identityv2/data/uploadXml")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Type": "multipart/form-data; boundary=----WebKitFormBoundaryMniLgY2y7IIAhTZ1",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"SESSION": "$entSession"})
            .upload(**{"file": "data/$fileName"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.message", "success")
            .assert_equal("body.status", 1)
            .assert_equal("body.data", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseUploadxml().test_start()
