# NOTE: Generated By HttpRunner v3.1.6
# FROM: testsuites/prefixAudit/prefix_audit_pageQuery_auditState_pass.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.prefixAudit.register_test import TestCaseRegister as Register

from testcases.login.login_ent_test import TestCaseLoginEnt as LoginEnt

from testcases.prefixAudit.register.upload_img_test import (
    TestCaseUploadImg as UploadImg,
)

from testcases.prefixAudit.register.upload_img_f_test import (
    TestCaseUploadImgF as UploadImgF,
)

from testcases.prefixAudit.register.upload_img_b_test import (
    TestCaseUploadImgB as UploadImgB,
)

from testcases.prefixAudit.register.submit_first_test import (
    TestCaseSubmitFirst as SubmitFirst,
)

from testcases.prefixAudit.register.apply_or_not_test import (
    TestCaseApplyOrNot as ApplyOrNot,
)

from testcases.prefixAudit.register.submit_second_test import (
    TestCaseSubmitSecond as SubmitSecond,
)

from testcases.prefixAudit.register.submit_final_test import (
    TestCaseSubmitFinal as SubmitFinal,
)

from testcases.login.login_admin_test import TestCaseLoginAdmin as LoginAdmin

from testcases.prefixAudit.audit.finance_rule_findRule_test import (
    TestCaseFinanceRuleFindrule as FinanceRuleFindrule,
)

from testcases.prefixAudit.audit.finance_rule_findRule_reg_test import (
    TestCaseFinanceRuleFindruleReg as FinanceRuleFindruleReg,
)

from testcases.prefixAudit.audit.v3_ent_audit_save_test import (
    TestCaseV3EntAuditSave as V3EntAuditSave,
)

from testcases.prefixAudit.audit.ent_prefix_manage_pageQuery_prefix_test import (
    TestCaseEntPrefixManagePagequeryPrefix as EntPrefixManagePagequeryPrefix,
)

from testcases.prefixAudit.audit.ent_audit_pageQuery_pass_test import (
    TestCaseEntAuditPagequeryPass as EntAuditPagequeryPass,
)


class TestCasePrefixAuditPagequeryAuditstatePass(HttpRunner):

    config = Config("前缀审核列表-查询状态为通过").variables(
        **{
            "email": "${get_email()}",
            "mobile": "${get_mobile()}",
            "username": "${get_username()}",
            "account": "${ENV(adminaccount)}",
            "password": "${ENV(adminpassword)}",
            "entaccount": "$username",
            "entpassword": "${ENV(entpassword)}",
            "orgNamePage": "",
            "entPrefixPage": "",
            "auditStatePage": "2",
            "rangeTimePage": "",
            "prefix": "${ENV(prefix_second)}${get_random_param(1,10000000000,1)}",
            "personId": "${get_idcardno()}",
        }
    )

    teststeps = [
        Step(RunTestCase("用户注册").call(Register)),
        Step(RunTestCase("登录-企业").call(LoginEnt).export(*["entSession"])),
        Step(RunTestCase("前缀注册企业资质图片上传").call(UploadImg).export(*["imgId"])),
        Step(RunTestCase("前缀注册企业联系人身份证图片正面上传").call(UploadImgF).export(*["imgId_f"])),
        Step(RunTestCase("前缀注册企业联系人身份证图片背面上传").call(UploadImgB).export(*["imgId_b"])),
        Step(RunTestCase("企业注册第一步提交信息").call(SubmitFirst)),
        Step(
            RunTestCase("企业注册查询注册信息")
            .call(ApplyOrNot)
            .export(
                *[
                    "entInfoSyss_3_deployAddrCity",
                    "contactPhone",
                    "entInfoSyss_2_deployAddrProvince",
                    "entInfoSyss_3_deployMode",
                    "legalPhone",
                    "entInfoSyss_0_sysType",
                    "orgCategorySpecificDesc",
                    "orgCrtImgRid",
                    "entInfoSyss_1_deployMode",
                    "entInfoSyss_2_deployMode",
                    "orgAddrProvince",
                    "entId",
                    "createDate",
                    "orgCrtType",
                    "entInfoSyss_3_entApplyId",
                    "applyId",
                    "entInfoSyss_2_deployAddr",
                    "entInfoSyss_2_entApplyId",
                    "userName",
                    "contactCrtType",
                    "entInfoSyss_1_id",
                    "imgId",
                    "orgAddr",
                    "entInfoSyss_0_deployAddrCity",
                    "entInfoSyss_1_deployAddrCity",
                    "entInfoSyss_1_deployAddrProvince",
                    "entInfoSyss_2_deployAddrCounty",
                    "imgId_f",
                    "industrySpecific",
                    "entInfoSyss_0_deployMode",
                    "legalCrtNo",
                    "entInfoSyss_3_deployAddr",
                    "entInfoSyss_3_deployAddrCounty",
                    "entInfoSyss_1_sysType",
                    "orgCrtCode",
                    "legalName",
                    "legalCrtType",
                    "orgAddrCountyDesc",
                    "entInfoSyss_2_deployAddrCity",
                    "entInfoSyss_3_id",
                    "entInfoSyss_2_id",
                    "entInfoSyss_2_sysType",
                    "legalCrtBackImgRid",
                    "legalCrtFrontImgRid",
                    "entInfoSyss_0_deployAddrCounty",
                    "imgId_b",
                    "orgAddrCounty",
                    "legalEmail",
                    "entInfoSyss_3_sysType",
                    "contactCrtNo",
                    "orgName",
                    "orgAddrCityDesc",
                    "orgNature",
                    "orgAddrProvinceDesc",
                    "entInfoSyss_0_id",
                    "contactEmail",
                    "contactName",
                    "updateDate",
                    "entInfoSyss_3_deployAddrProvince",
                    "industryCategory",
                    "entInfoSyss_0_entApplyId",
                    "legalCrtTypeDesc",
                    "entApplyId",
                    "userId",
                    "orgNatureDesc",
                    "entInfoSyss_1_entApplyId",
                    "entInfoSyss_0_deployAddrProvince",
                    "entInfoSyss_1_deployAddrCounty",
                    "entInfoSyss_1_deployAddr",
                    "entInfoSyss_0_deployAddr",
                    "orgAddrCity",
                    "entUserId",
                    "prefix",
                ]
            )
        ),
        Step(RunTestCase("企业注册第二步提交信息").call(SubmitSecond)),
        Step(
            RunTestCase("企业注册查询注册信息")
            .call(ApplyOrNot)
            .export(
                *[
                    "entInfoSyss_3_deployAddrCity",
                    "contactPhone",
                    "entInfoSyss_2_deployAddrProvince",
                    "entInfoSyss_3_deployMode",
                    "legalPhone",
                    "entInfoSyss_0_sysType",
                    "orgCategorySpecificDesc",
                    "orgCrtImgRid",
                    "entInfoSyss_1_deployMode",
                    "entInfoSyss_2_deployMode",
                    "orgAddrProvince",
                    "entId",
                    "createDate",
                    "orgCrtType",
                    "entInfoSyss_3_entApplyId",
                    "applyId",
                    "entInfoSyss_2_deployAddr",
                    "entInfoSyss_2_entApplyId",
                    "userName",
                    "contactCrtType",
                    "entInfoSyss_1_id",
                    "imgId",
                    "orgAddr",
                    "entInfoSyss_0_deployAddrCity",
                    "entInfoSyss_1_deployAddrCity",
                    "entInfoSyss_1_deployAddrProvince",
                    "entInfoSyss_2_deployAddrCounty",
                    "imgId_f",
                    "industrySpecific",
                    "entInfoSyss_0_deployMode",
                    "legalCrtNo",
                    "entInfoSyss_3_deployAddr",
                    "entInfoSyss_3_deployAddrCounty",
                    "entInfoSyss_1_sysType",
                    "orgCrtCode",
                    "legalName",
                    "legalCrtType",
                    "orgAddrCountyDesc",
                    "entInfoSyss_2_deployAddrCity",
                    "entInfoSyss_3_id",
                    "entInfoSyss_2_id",
                    "entInfoSyss_2_sysType",
                    "legalCrtBackImgRid",
                    "legalCrtFrontImgRid",
                    "entInfoSyss_0_deployAddrCounty",
                    "imgId_b",
                    "orgAddrCounty",
                    "legalEmail",
                    "entInfoSyss_3_sysType",
                    "contactCrtNo",
                    "orgName",
                    "orgAddrCityDesc",
                    "orgNature",
                    "orgAddrProvinceDesc",
                    "entInfoSyss_0_id",
                    "contactEmail",
                    "contactName",
                    "updateDate",
                    "entInfoSyss_3_deployAddrProvince",
                    "industryCategory",
                    "entInfoSyss_0_entApplyId",
                    "legalCrtTypeDesc",
                    "entApplyId",
                    "userId",
                    "orgNatureDesc",
                    "entInfoSyss_1_entApplyId",
                    "entInfoSyss_0_deployAddrProvince",
                    "entInfoSyss_1_deployAddrCounty",
                    "entInfoSyss_1_deployAddr",
                    "entInfoSyss_0_deployAddr",
                    "orgAddrCity",
                    "entUserId",
                    "prefix",
                ]
            )
        ),
        Step(RunTestCase("企业注册最终第三步提交信息").call(SubmitFinal)),
        Step(RunTestCase("登录-管理员").call(LoginAdmin).export(*["adminSession"])),
        Step(
            RunTestCase("年费费用查询").call(FinanceRuleFindrule).export(*["annualFeeRuleId"])
        ),
        Step(
            RunTestCase("注册费费用查询")
            .call(FinanceRuleFindruleReg)
            .export(*["regFeeRuleId"])
        ),
        Step(RunTestCase("审核结果保存").call(V3EntAuditSave)),
        Step(
            RunTestCase("前缀管理分页")
            .call(EntPrefixManagePagequeryPrefix)
            .export(*["prefixId", "entPrefix", "userId", "proxyState", "entNameCn"])
        ),
        Step(RunTestCase("企业审核分页").call(EntAuditPagequeryPass)),
    ]


if __name__ == "__main__":
    TestCasePrefixAuditPagequeryAuditstatePass().test_start()
