# NOTE: Generated By HttpRunner v3.1.6
# FROM: testsuites/prefixAudit/test_update_prefix_audit_success.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.prefixAudit.register_test import TestCaseRegister as Register

from testcases.login.login_ent_test import TestCaseLoginEnt as LoginEnt

from testcases.prefixAudit.register.upload_img_test import (
    TestCaseUploadImg as UploadImg,
)

from testcases.prefixAudit.register.upload_img_f_test import (
    TestCaseUploadImgF as UploadImgF,
)

from testcases.prefixAudit.register.upload_img_b_test import (
    TestCaseUploadImgB as UploadImgB,
)

from testcases.prefixAudit.register.submit_first_test import (
    TestCaseSubmitFirst as SubmitFirst,
)

from testcases.prefixAudit.register.apply_or_not_test import (
    TestCaseApplyOrNot as ApplyOrNot,
)

from testcases.prefixAudit.register.submit_second_test import (
    TestCaseSubmitSecond as SubmitSecond,
)

from testcases.prefixAudit.register.submit_final_test import (
    TestCaseSubmitFinal as SubmitFinal,
)

from testcases.login.login_admin_test import TestCaseLoginAdmin as LoginAdmin

from testcases.prefixAudit.audit.finance_rule_findRule_test import (
    TestCaseFinanceRuleFindrule as FinanceRuleFindrule,
)

from testcases.prefixAudit.audit.finance_rule_findRule_reg_test import (
    TestCaseFinanceRuleFindruleReg as FinanceRuleFindruleReg,
)

from testcases.prefixAudit.audit.v3_ent_audit_save_test import (
    TestCaseV3EntAuditSave as V3EntAuditSave,
)

from testcases.prefixAudit.audit.ent_prefix_manage_pageQuery_prefix_test import (
    TestCaseEntPrefixManagePagequeryPrefix as EntPrefixManagePagequeryPrefix,
)

from testcases.prefixAudit.register.apply_or_not_getid_test import (
    TestCaseApplyOrNotGetid as ApplyOrNotGetid,
)

from testcases.prefixAudit.register.update_submit_first_test import (
    TestCaseUpdateSubmitFirst as UpdateSubmitFirst,
)

from testcases.prefixAudit.register.submit_final_update_test import (
    TestCaseSubmitFinalUpdate as SubmitFinalUpdate,
)

from testcases.prefixAudit.audit.v3_ent_audit_save_entprefix_test import (
    TestCaseV3EntAuditSaveEntprefix as V3EntAuditSaveEntprefix,
)


class TestCaseTestUpdatePrefixAuditSuccess(HttpRunner):

    config = (
        Config("重新申请")
        .variables(
            **{
                "entprefix": "${ENV(prefix_second)}${get_random_param(1000,10000000000,1)}",
                "email": "${get_email()}",
                "mobile": "${get_mobile()}",
                "username": "${get_username()}",
                "account": "${ENV(adminaccount)}",
                "password": "${ENV(adminpassword)}",
                "entaccount": "$username",
                "entpassword": "${ENV(entpassword)}",
                "prefix": "${ENV(prefix_second)}${get_random_param(1000,10000000000,1)}",
                "personId": "${get_idcardno()}",
            }
        )
        .export(*["applyId", "prefix"])
    )

    teststeps = [
        Step(RunTestCase("用户注册").call(Register)),
        Step(RunTestCase("登录-企业").call(LoginEnt).export(*["entSession"])),
        Step(RunTestCase("前缀注册企业资质图片上传").call(UploadImg).export(*["imgId"])),
        Step(RunTestCase("前缀注册企业联系人身份证图片正面上传").call(UploadImgF).export(*["imgId_f"])),
        Step(RunTestCase("前缀注册企业联系人身份证图片背面上传").call(UploadImgB).export(*["imgId_b"])),
        Step(RunTestCase("企业注册第一步提交信息").call(SubmitFirst)),
        Step(
            RunTestCase("企业注册查询注册信息")
            .call(ApplyOrNot)
            .export(
                *[
                    "applyId",
                    "orgAddrCity",
                    "orgAddrCountyDesc",
                    "entInfoSyss_0_sysType",
                    "entInfoSyss_3_deployAddrCity",
                    "orgCrtCode",
                    "entInfoSyss_1_deployAddr",
                    "entInfoSyss_2_sysType",
                    "contactCrtType",
                    "orgNatureDesc",
                    "entUserId",
                    "orgCrtType",
                    "entInfoSyss_2_entApplyId",
                    "orgNature",
                    "entInfoSyss_3_entApplyId",
                    "contactPhone",
                    "entInfoSyss_3_deployAddr",
                    "industrySpecific",
                    "createDate",
                    "legalName",
                    "legalCrtNo",
                    "orgAddr",
                    "entInfoSyss_3_deployAddrProvince",
                    "entId",
                    "entInfoSyss_2_id",
                    "entApplyId",
                    "legalEmail",
                    "entInfoSyss_3_sysType",
                    "entInfoSyss_2_deployAddrCity",
                    "entInfoSyss_1_entApplyId",
                    "userName",
                    "entInfoSyss_3_deployMode",
                    "entInfoSyss_2_deployAddrCounty",
                    "updateDate",
                    "entInfoSyss_3_id",
                    "entInfoSyss_0_deployMode",
                    "entInfoSyss_1_deployAddrProvince",
                    "imgId_b",
                    "orgName",
                    "entInfoSyss_0_deployAddr",
                    "entInfoSyss_3_deployAddrCounty",
                    "legalCrtTypeDesc",
                    "imgId",
                    "entInfoSyss_0_entApplyId",
                    "entInfoSyss_1_id",
                    "entInfoSyss_1_deployMode",
                    "industryCategory",
                    "orgAddrProvince",
                    "legalCrtBackImgRid",
                    "entInfoSyss_2_deployAddr",
                    "imgId_f",
                    "orgAddrCounty",
                    "entInfoSyss_1_deployAddrCounty",
                    "entInfoSyss_0_deployAddrCounty",
                    "legalPhone",
                    "legalCrtFrontImgRid",
                    "prefix",
                    "orgAddrProvinceDesc",
                    "entInfoSyss_2_deployAddrProvince",
                    "contactName",
                    "orgAddrCityDesc",
                    "userId",
                    "contactCrtNo",
                    "entInfoSyss_2_deployMode",
                    "contactEmail",
                    "entInfoSyss_1_sysType",
                    "entInfoSyss_0_deployAddrCity",
                    "orgCrtImgRid",
                    "entInfoSyss_1_deployAddrCity",
                    "entInfoSyss_0_deployAddrProvince",
                    "orgCategorySpecificDesc",
                    "legalCrtType",
                    "entInfoSyss_0_id",
                ]
            )
        ),
        Step(RunTestCase("企业注册第二步提交信息").call(SubmitSecond)),
        Step(
            RunTestCase("企业注册查询注册信息")
            .call(ApplyOrNot)
            .export(
                *[
                    "applyId",
                    "orgAddrCity",
                    "orgAddrCountyDesc",
                    "entInfoSyss_0_sysType",
                    "entInfoSyss_3_deployAddrCity",
                    "orgCrtCode",
                    "entInfoSyss_1_deployAddr",
                    "entInfoSyss_2_sysType",
                    "contactCrtType",
                    "orgNatureDesc",
                    "entUserId",
                    "orgCrtType",
                    "entInfoSyss_2_entApplyId",
                    "orgNature",
                    "entInfoSyss_3_entApplyId",
                    "contactPhone",
                    "entInfoSyss_3_deployAddr",
                    "industrySpecific",
                    "createDate",
                    "legalName",
                    "legalCrtNo",
                    "orgAddr",
                    "entInfoSyss_3_deployAddrProvince",
                    "entId",
                    "entInfoSyss_2_id",
                    "entApplyId",
                    "legalEmail",
                    "entInfoSyss_3_sysType",
                    "entInfoSyss_2_deployAddrCity",
                    "entInfoSyss_1_entApplyId",
                    "userName",
                    "entInfoSyss_3_deployMode",
                    "entInfoSyss_2_deployAddrCounty",
                    "updateDate",
                    "entInfoSyss_3_id",
                    "entInfoSyss_0_deployMode",
                    "entInfoSyss_1_deployAddrProvince",
                    "imgId_b",
                    "orgName",
                    "entInfoSyss_0_deployAddr",
                    "entInfoSyss_3_deployAddrCounty",
                    "legalCrtTypeDesc",
                    "imgId",
                    "entInfoSyss_0_entApplyId",
                    "entInfoSyss_1_id",
                    "entInfoSyss_1_deployMode",
                    "industryCategory",
                    "orgAddrProvince",
                    "legalCrtBackImgRid",
                    "entInfoSyss_2_deployAddr",
                    "imgId_f",
                    "orgAddrCounty",
                    "entInfoSyss_1_deployAddrCounty",
                    "entInfoSyss_0_deployAddrCounty",
                    "legalPhone",
                    "legalCrtFrontImgRid",
                    "prefix",
                    "orgAddrProvinceDesc",
                    "entInfoSyss_2_deployAddrProvince",
                    "contactName",
                    "orgAddrCityDesc",
                    "userId",
                    "contactCrtNo",
                    "entInfoSyss_2_deployMode",
                    "contactEmail",
                    "entInfoSyss_1_sysType",
                    "entInfoSyss_0_deployAddrCity",
                    "orgCrtImgRid",
                    "entInfoSyss_1_deployAddrCity",
                    "entInfoSyss_0_deployAddrProvince",
                    "orgCategorySpecificDesc",
                    "legalCrtType",
                    "entInfoSyss_0_id",
                ]
            )
        ),
        Step(RunTestCase("企业注册最终第三步提交信息").call(SubmitFinal)),
        Step(RunTestCase("登录-管理员").call(LoginAdmin).export(*["adminSession"])),
        Step(
            RunTestCase("年费费用查询").call(FinanceRuleFindrule).export(*["annualFeeRuleId"])
        ),
        Step(
            RunTestCase("注册费费用查询")
            .call(FinanceRuleFindruleReg)
            .export(*["regFeeRuleId"])
        ),
        Step(RunTestCase("审核结果保存").call(V3EntAuditSave)),
        Step(
            RunTestCase("前缀管理分页")
            .call(EntPrefixManagePagequeryPrefix)
            .export(*["entPrefix", "proxyState", "userId", "prefixId", "entNameCn"])
        ),
        Step(RunTestCase("登录-企业").call(LoginEnt).export(*["entSession"])),
        Step(
            RunTestCase("获取申请id")
            .call(ApplyOrNotGetid)
            .export(
                *[
                    "applyId",
                    "orgAddrCity",
                    "orgAddrCountyDesc",
                    "entInfoSyss_0_sysType",
                    "entInfoSyss_3_deployAddrCity",
                    "orgCrtCode",
                    "entInfoSyss_1_deployAddr",
                    "entInfoSyss_2_sysType",
                    "contactCrtType",
                    "orgNatureDesc",
                    "entUserId",
                    "orgCrtType",
                    "entInfoSyss_2_entApplyId",
                    "orgNature",
                    "entInfoSyss_3_entApplyId",
                    "contactPhone",
                    "entInfoSyss_3_deployAddr",
                    "industrySpecific",
                    "createDate",
                    "legalName",
                    "legalCrtNo",
                    "orgAddr",
                    "entInfoSyss_3_deployAddrProvince",
                    "entId",
                    "entInfoSyss_2_id",
                    "entApplyId",
                    "legalEmail",
                    "entInfoSyss_3_sysType",
                    "entInfoSyss_2_deployAddrCity",
                    "entInfoSyss_1_entApplyId",
                    "userName",
                    "entInfoSyss_3_deployMode",
                    "entInfoSyss_2_deployAddrCounty",
                    "updateDate",
                    "entInfoSyss_3_id",
                    "entInfoSyss_0_deployMode",
                    "entInfoSyss_1_deployAddrProvince",
                    "imgId_b",
                    "orgName",
                    "entInfoSyss_0_deployAddr",
                    "entInfoSyss_3_deployAddrCounty",
                    "legalCrtTypeDesc",
                    "imgId",
                    "entInfoSyss_0_entApplyId",
                    "entInfoSyss_1_id",
                    "entInfoSyss_1_deployMode",
                    "industryCategory",
                    "orgAddrProvince",
                    "legalCrtBackImgRid",
                    "entInfoSyss_2_deployAddr",
                    "imgId_f",
                    "orgAddrCounty",
                    "entInfoSyss_1_deployAddrCounty",
                    "entInfoSyss_0_deployAddrCounty",
                    "legalPhone",
                    "legalCrtFrontImgRid",
                    "prefix",
                    "orgAddrProvinceDesc",
                    "entInfoSyss_2_deployAddrProvince",
                    "contactName",
                    "orgAddrCityDesc",
                    "userId",
                    "contactCrtNo",
                    "entInfoSyss_2_deployMode",
                    "contactEmail",
                    "entInfoSyss_1_sysType",
                    "entInfoSyss_0_deployAddrCity",
                    "orgCrtImgRid",
                    "entInfoSyss_1_deployAddrCity",
                    "entInfoSyss_0_deployAddrProvince",
                    "orgCategorySpecificDesc",
                    "legalCrtType",
                    "entInfoSyss_0_id",
                ]
            )
        ),
        Step(RunTestCase("前缀注册企业资质图片上传").call(UploadImg).export(*["imgId"])),
        Step(RunTestCase("前缀注册企业联系人身份证图片正面上传").call(UploadImgF).export(*["imgId_f"])),
        Step(RunTestCase("前缀注册企业联系人身份证图片背面上传").call(UploadImgB).export(*["imgId_b"])),
        Step(RunTestCase("企业注册第一步提交信息").call(UpdateSubmitFirst)),
        Step(
            RunTestCase("企业注册查询注册信息")
            .call(ApplyOrNot)
            .export(
                *[
                    "applyId",
                    "orgAddrCity",
                    "orgAddrCountyDesc",
                    "entInfoSyss_0_sysType",
                    "entInfoSyss_3_deployAddrCity",
                    "orgCrtCode",
                    "entInfoSyss_1_deployAddr",
                    "entInfoSyss_2_sysType",
                    "contactCrtType",
                    "orgNatureDesc",
                    "entUserId",
                    "orgCrtType",
                    "entInfoSyss_2_entApplyId",
                    "orgNature",
                    "entInfoSyss_3_entApplyId",
                    "contactPhone",
                    "entInfoSyss_3_deployAddr",
                    "industrySpecific",
                    "createDate",
                    "legalName",
                    "legalCrtNo",
                    "orgAddr",
                    "entInfoSyss_3_deployAddrProvince",
                    "entId",
                    "entInfoSyss_2_id",
                    "entApplyId",
                    "legalEmail",
                    "entInfoSyss_3_sysType",
                    "entInfoSyss_2_deployAddrCity",
                    "entInfoSyss_1_entApplyId",
                    "userName",
                    "entInfoSyss_3_deployMode",
                    "entInfoSyss_2_deployAddrCounty",
                    "updateDate",
                    "entInfoSyss_3_id",
                    "entInfoSyss_0_deployMode",
                    "entInfoSyss_1_deployAddrProvince",
                    "imgId_b",
                    "orgName",
                    "entInfoSyss_0_deployAddr",
                    "entInfoSyss_3_deployAddrCounty",
                    "legalCrtTypeDesc",
                    "imgId",
                    "entInfoSyss_0_entApplyId",
                    "entInfoSyss_1_id",
                    "entInfoSyss_1_deployMode",
                    "industryCategory",
                    "orgAddrProvince",
                    "legalCrtBackImgRid",
                    "entInfoSyss_2_deployAddr",
                    "imgId_f",
                    "orgAddrCounty",
                    "entInfoSyss_1_deployAddrCounty",
                    "entInfoSyss_0_deployAddrCounty",
                    "legalPhone",
                    "legalCrtFrontImgRid",
                    "prefix",
                    "orgAddrProvinceDesc",
                    "entInfoSyss_2_deployAddrProvince",
                    "contactName",
                    "orgAddrCityDesc",
                    "userId",
                    "contactCrtNo",
                    "entInfoSyss_2_deployMode",
                    "contactEmail",
                    "entInfoSyss_1_sysType",
                    "entInfoSyss_0_deployAddrCity",
                    "orgCrtImgRid",
                    "entInfoSyss_1_deployAddrCity",
                    "entInfoSyss_0_deployAddrProvince",
                    "orgCategorySpecificDesc",
                    "legalCrtType",
                    "entInfoSyss_0_id",
                ]
            )
        ),
        Step(RunTestCase("企业注册第二步提交信息").call(SubmitSecond)),
        Step(
            RunTestCase("企业注册查询注册信息")
            .call(ApplyOrNot)
            .export(
                *[
                    "applyId",
                    "orgAddrCity",
                    "orgAddrCountyDesc",
                    "entInfoSyss_0_sysType",
                    "entInfoSyss_3_deployAddrCity",
                    "orgCrtCode",
                    "entInfoSyss_1_deployAddr",
                    "entInfoSyss_2_sysType",
                    "contactCrtType",
                    "orgNatureDesc",
                    "entUserId",
                    "orgCrtType",
                    "entInfoSyss_2_entApplyId",
                    "orgNature",
                    "entInfoSyss_3_entApplyId",
                    "contactPhone",
                    "entInfoSyss_3_deployAddr",
                    "industrySpecific",
                    "createDate",
                    "legalName",
                    "legalCrtNo",
                    "orgAddr",
                    "entInfoSyss_3_deployAddrProvince",
                    "entId",
                    "entInfoSyss_2_id",
                    "entApplyId",
                    "legalEmail",
                    "entInfoSyss_3_sysType",
                    "entInfoSyss_2_deployAddrCity",
                    "entInfoSyss_1_entApplyId",
                    "userName",
                    "entInfoSyss_3_deployMode",
                    "entInfoSyss_2_deployAddrCounty",
                    "updateDate",
                    "entInfoSyss_3_id",
                    "entInfoSyss_0_deployMode",
                    "entInfoSyss_1_deployAddrProvince",
                    "imgId_b",
                    "orgName",
                    "entInfoSyss_0_deployAddr",
                    "entInfoSyss_3_deployAddrCounty",
                    "legalCrtTypeDesc",
                    "imgId",
                    "entInfoSyss_0_entApplyId",
                    "entInfoSyss_1_id",
                    "entInfoSyss_1_deployMode",
                    "industryCategory",
                    "orgAddrProvince",
                    "legalCrtBackImgRid",
                    "entInfoSyss_2_deployAddr",
                    "imgId_f",
                    "orgAddrCounty",
                    "entInfoSyss_1_deployAddrCounty",
                    "entInfoSyss_0_deployAddrCounty",
                    "legalPhone",
                    "legalCrtFrontImgRid",
                    "prefix",
                    "orgAddrProvinceDesc",
                    "entInfoSyss_2_deployAddrProvince",
                    "contactName",
                    "orgAddrCityDesc",
                    "userId",
                    "contactCrtNo",
                    "entInfoSyss_2_deployMode",
                    "contactEmail",
                    "entInfoSyss_1_sysType",
                    "entInfoSyss_0_deployAddrCity",
                    "orgCrtImgRid",
                    "entInfoSyss_1_deployAddrCity",
                    "entInfoSyss_0_deployAddrProvince",
                    "orgCategorySpecificDesc",
                    "legalCrtType",
                    "entInfoSyss_0_id",
                ]
            )
        ),
        Step(RunTestCase("企业注册最终第三步提交信息").call(SubmitFinalUpdate)),
        Step(RunTestCase("登录-管理员").call(LoginAdmin).export(*["adminSession"])),
        Step(
            RunTestCase("年费费用查询").call(FinanceRuleFindrule).export(*["annualFeeRuleId"])
        ),
        Step(
            RunTestCase("注册费费用查询")
            .call(FinanceRuleFindruleReg)
            .export(*["regFeeRuleId"])
        ),
        Step(RunTestCase("审核结果保存").call(V3EntAuditSaveEntprefix)),
    ]


if __name__ == "__main__":
    TestCaseTestUpdatePrefixAuditSuccess().test_start()
