# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/handle/handleDelete-ent.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseHandledeleteEnt(HttpRunner):

    config = Config("标识删除").base_url("${ENV(HOST)}").verify(False)

    teststeps = [
        Step(
            RunRequest("标识删除")
            .post("/api/snms/identityv2/data")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "33",
                    "Content-Type": "application/json;charset=UTF-8",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                    "X-HTTP-Method-Override": "delete",
                }
            )
            .with_cookies(**{"SESSION": "$entSession"})
            .with_json({"handle": "$handle"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.message", "success")
            .assert_equal("body.status", 1)
            .assert_equal("body.data", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseHandledeleteEnt().test_start()
