# NOTE: Generated By HttpRunner v3.1.6
# FROM: testsuites/logmanager/userlog.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.login.login_admin_test import TestCaseLoginAdmin as LoginAdmin

from testcases.logmanager.userlog_test import TestCaseUserlog as Userlog


class TestCaseUserlog(HttpRunner):

    config = Config("用户日志记录").variables(
        **{"account": "${ENV(adminaccount)}", "password": "${ENV(adminpassword)}"}
    )

    teststeps = [
        Step(RunTestCase("管理员用户登录").call(LoginAdmin).export(*["adminSession"])),
        Step(RunTestCase("用户日志列表").call(Userlog)),
    ]


if __name__ == "__main__":
    TestCaseUserlog().test_start()
