# NOTE: Generated By HttpRunner v3.1.6
# FROM: testsuites/handle/test_handle_resolve_withChineseValue.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.prefixAudit.register_test import TestCaseRegister as Register

from testcases.login.login_ent_test import TestCaseLoginEnt as LoginEnt

from testcases.prefixAudit.register.upload_img_test import (
    TestCaseUploadImg as UploadImg,
)

from testcases.prefixAudit.register.upload_img_f_test import (
    TestCaseUploadImgF as UploadImgF,
)

from testcases.prefixAudit.register.upload_img_b_test import (
    TestCaseUploadImgB as UploadImgB,
)

from testcases.prefixAudit.register.submit_first_test import (
    TestCaseSubmitFirst as SubmitFirst,
)

from testcases.prefixAudit.register.apply_or_not_test import (
    TestCaseApplyOrNot as ApplyOrNot,
)

from testcases.prefixAudit.register.submit_second_test import (
    TestCaseSubmitSecond as SubmitSecond,
)

from testcases.prefixAudit.register.submit_final_test import (
    TestCaseSubmitFinal as SubmitFinal,
)

from testcases.login.login_admin_test import TestCaseLoginAdmin as LoginAdmin

from testcases.prefixAudit.audit.finance_rule_findRule_test import (
    TestCaseFinanceRuleFindrule as FinanceRuleFindrule,
)

from testcases.prefixAudit.audit.finance_rule_findRule_reg_test import (
    TestCaseFinanceRuleFindruleReg as FinanceRuleFindruleReg,
)

from testcases.prefixAudit.audit.v3_ent_audit_save_test import (
    TestCaseV3EntAuditSave as V3EntAuditSave,
)

from testcases.prefixAudit.audit.ent_prefix_manage_pageQuery_prefix_test import (
    TestCaseEntPrefixManagePagequeryPrefix as EntPrefixManagePagequeryPrefix,
)

from testcases.proxyAudit.proxy_apply_test import TestCaseProxyApply as ProxyApply

from testcases.prefixAudit.proxyserverauditlist_test import (
    TestCaseProxyserverauditlist as Proxyserverauditlist,
)

from testcases.proxyAudit.proxyserverlist_test import (
    TestCaseProxyserverlist as Proxyserverlist,
)

from testcases.proxyAudit.proxyserverprefixaudit_test import (
    TestCaseProxyserverprefixaudit as Proxyserverprefixaudit,
)

from testcases.template.templateCreate_test import (
    TestCaseTemplatecreate as Templatecreate,
)

from testcases.handle.handleCreate_ent_test import (
    TestCaseHandlecreateEnt as HandlecreateEnt,
)

from testcases.handle.resolveHandle_test import TestCaseResolvehandle as Resolvehandle


class TestCaseTestHandleResolveWithchinesevalue(HttpRunner):

    config = Config("用申报的模板递归解析，显示模板中中文名称属性-12").variables(
        **{
            "handle": "${prefix}/${get_random_param(100000,1000000,1)}",
            "version": "zjauto${get_random_param(1,10000,1)}",
            "email": "${get_email()}",
            "mobile": "${get_mobile()}",
            "username": "${get_username()}",
            "account": "${ENV(adminaccount)}",
            "password": "${ENV(adminpassword)}",
            "entaccount": "$username",
            "entpassword": "${ENV(entpassword)}",
            "prefix": "${ENV(prefix_second)}${get_random_param(1000,10000000000,1)}",
            "personId": "${get_idcardno()}",
        }
    )

    teststeps = [
        Step(RunTestCase("用户注册").call(Register)),
        Step(RunTestCase("登录-企业").call(LoginEnt).export(*["entSession"])),
        Step(RunTestCase("前缀注册企业资质图片上传").call(UploadImg).export(*["imgId"])),
        Step(RunTestCase("前缀注册企业联系人身份证图片正面上传").call(UploadImgF).export(*["imgId_f"])),
        Step(RunTestCase("前缀注册企业联系人身份证图片背面上传").call(UploadImgB).export(*["imgId_b"])),
        Step(RunTestCase("企业注册第一步提交信息").call(SubmitFirst)),
        Step(
            RunTestCase("企业注册查询注册信息")
            .call(ApplyOrNot)
            .export(
                *[
                    "orgCrtType",
                    "legalCrtFrontImgRid",
                    "entInfoSyss_1_deployAddrCounty",
                    "entInfoSyss_2_deployAddrCity",
                    "entInfoSyss_0_entApplyId",
                    "entInfoSyss_2_deployAddrCounty",
                    "entInfoSyss_2_deployMode",
                    "entInfoSyss_1_entApplyId",
                    "orgAddrCounty",
                    "entInfoSyss_3_deployAddrProvince",
                    "entInfoSyss_2_entApplyId",
                    "legalCrtBackImgRid",
                    "orgAddrProvinceDesc",
                    "legalEmail",
                    "entInfoSyss_3_deployAddrCity",
                    "contactCrtNo",
                    "entInfoSyss_1_deployMode",
                    "imgId_f",
                    "entInfoSyss_3_deployMode",
                    "legalName",
                    "legalCrtType",
                    "entInfoSyss_3_deployAddrCounty",
                    "entInfoSyss_2_deployAddrProvince",
                    "updateDate",
                    "contactPhone",
                    "orgAddrCity",
                    "legalCrtTypeDesc",
                    "createDate",
                    "entInfoSyss_3_id",
                    "orgNatureDesc",
                    "orgAddrCountyDesc",
                    "orgAddrProvince",
                    "entInfoSyss_0_deployAddrProvince",
                    "entInfoSyss_3_entApplyId",
                    "legalCrtNo",
                    "orgAddrCityDesc",
                    "imgId",
                    "orgCrtCode",
                    "orgCrtImgRid",
                    "userName",
                    "entInfoSyss_0_sysType",
                    "entInfoSyss_1_deployAddrProvince",
                    "entInfoSyss_2_deployAddr",
                    "legalPhone",
                    "prefix",
                    "contactEmail",
                    "entInfoSyss_0_id",
                    "entInfoSyss_2_id",
                    "orgName",
                    "applyId",
                    "imgId_b",
                    "entInfoSyss_0_deployAddrCity",
                    "entInfoSyss_0_deployAddrCounty",
                    "entInfoSyss_1_deployAddr",
                    "entInfoSyss_3_sysType",
                    "entInfoSyss_1_deployAddrCity",
                    "orgCategorySpecificDesc",
                    "entInfoSyss_1_sysType",
                    "entApplyId",
                    "contactName",
                    "entInfoSyss_0_deployAddr",
                    "entInfoSyss_0_deployMode",
                    "entInfoSyss_3_deployAddr",
                    "entInfoSyss_2_sysType",
                    "contactCrtType",
                    "entUserId",
                    "entId",
                    "userId",
                    "orgNature",
                    "orgAddr",
                    "entInfoSyss_1_id",
                    "industryCategory",
                    "industrySpecific",
                ]
            )
        ),
        Step(RunTestCase("企业注册第二步提交信息").call(SubmitSecond)),
        Step(
            RunTestCase("企业注册查询注册信息")
            .call(ApplyOrNot)
            .export(
                *[
                    "orgCrtType",
                    "legalCrtFrontImgRid",
                    "entInfoSyss_1_deployAddrCounty",
                    "entInfoSyss_2_deployAddrCity",
                    "entInfoSyss_0_entApplyId",
                    "entInfoSyss_2_deployAddrCounty",
                    "entInfoSyss_2_deployMode",
                    "entInfoSyss_1_entApplyId",
                    "orgAddrCounty",
                    "entInfoSyss_3_deployAddrProvince",
                    "entInfoSyss_2_entApplyId",
                    "legalCrtBackImgRid",
                    "orgAddrProvinceDesc",
                    "legalEmail",
                    "entInfoSyss_3_deployAddrCity",
                    "contactCrtNo",
                    "entInfoSyss_1_deployMode",
                    "imgId_f",
                    "entInfoSyss_3_deployMode",
                    "legalName",
                    "legalCrtType",
                    "entInfoSyss_3_deployAddrCounty",
                    "entInfoSyss_2_deployAddrProvince",
                    "updateDate",
                    "contactPhone",
                    "orgAddrCity",
                    "legalCrtTypeDesc",
                    "createDate",
                    "entInfoSyss_3_id",
                    "orgNatureDesc",
                    "orgAddrCountyDesc",
                    "orgAddrProvince",
                    "entInfoSyss_0_deployAddrProvince",
                    "entInfoSyss_3_entApplyId",
                    "legalCrtNo",
                    "orgAddrCityDesc",
                    "imgId",
                    "orgCrtCode",
                    "orgCrtImgRid",
                    "userName",
                    "entInfoSyss_0_sysType",
                    "entInfoSyss_1_deployAddrProvince",
                    "entInfoSyss_2_deployAddr",
                    "legalPhone",
                    "prefix",
                    "contactEmail",
                    "entInfoSyss_0_id",
                    "entInfoSyss_2_id",
                    "orgName",
                    "applyId",
                    "imgId_b",
                    "entInfoSyss_0_deployAddrCity",
                    "entInfoSyss_0_deployAddrCounty",
                    "entInfoSyss_1_deployAddr",
                    "entInfoSyss_3_sysType",
                    "entInfoSyss_1_deployAddrCity",
                    "orgCategorySpecificDesc",
                    "entInfoSyss_1_sysType",
                    "entApplyId",
                    "contactName",
                    "entInfoSyss_0_deployAddr",
                    "entInfoSyss_0_deployMode",
                    "entInfoSyss_3_deployAddr",
                    "entInfoSyss_2_sysType",
                    "contactCrtType",
                    "entUserId",
                    "entId",
                    "userId",
                    "orgNature",
                    "orgAddr",
                    "entInfoSyss_1_id",
                    "industryCategory",
                    "industrySpecific",
                ]
            )
        ),
        Step(RunTestCase("企业注册最终第三步提交信息").call(SubmitFinal)),
        Step(RunTestCase("登录-管理员").call(LoginAdmin).export(*["adminSession"])),
        Step(
            RunTestCase("年费费用查询").call(FinanceRuleFindrule).export(*["annualFeeRuleId"])
        ),
        Step(
            RunTestCase("注册费费用查询")
            .call(FinanceRuleFindruleReg)
            .export(*["regFeeRuleId"])
        ),
        Step(RunTestCase("审核结果保存").call(V3EntAuditSave)),
        Step(
            RunTestCase("前缀管理分页")
            .call(EntPrefixManagePagequeryPrefix)
            .export(*["entNameCn", "proxyState", "prefixId", "entPrefix", "userId"])
        ),
        Step(RunTestCase("企业用户登录").call(LoginEnt).export(*["entSession"])),
        Step(RunTestCase("企业申请托管").call(ProxyApply)),
        Step(RunTestCase("管理员登录").call(LoginAdmin).export(*["adminSession"])),
        Step(
            RunTestCase("前缀审核列表查询所申请前缀的id")
            .call(Proxyserverauditlist)
            .export(*["prefixauditid"])
        ),
        Step(RunTestCase("获取托管服务器列表").call(Proxyserverlist).export(*["proxyserverid"])),
        Step(RunTestCase("前缀审核通过").call(Proxyserverprefixaudit)),
        Step(RunTestCase("企业用户登录").call(LoginEnt).export(*["entSession"])),
        Step(RunTestCase("数据模板创建").call(Templatecreate)),
        Step(RunTestCase("标识注册").call(HandlecreateEnt)),
        Step(RunTestCase("二级系统门户查询已托管标识信息").call(Resolvehandle)),
    ]


if __name__ == "__main__":
    TestCaseTestHandleResolveWithchinesevalue().test_start()
