# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/verification/ent-apply-verification-legalIdentify.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseEntApplyVerificationLegalidentify(HttpRunner):

    config = (
        Config("核验接口")
        .variables(**{"entApplyId": "$entApplyId"})
        .base_url("${ENV(HOST)}")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("核验接口")
            .get("/api/ent/apply/verification/legalIdentify")
            .with_params(**{"entApplyId": "$entApplyId"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.56",
                }
            )
            .with_cookies(**{"SESSION": "adminSession"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.message", "success")
            .assert_equal("body.status", 1)
        ),
    ]


if __name__ == "__main__":
    TestCaseEntApplyVerificationLegalidentify().test_start()
