# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/idhub/idhub-parse-pass.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseIdhubParsePass(HttpRunner):

    config = Config("idhub解析标识-通过").base_url("${ENV(idhub_HOST)}").verify(False)

    teststeps = [
        Step(
            RunRequest("idhub解析标识")
            .get("api/handles/$idhub_biaoshi")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseIdhubParsePass().test_start()
