# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/idhub/idhubhomeprefrix.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseIdhubhomeprefrix(HttpRunner):

    config = Config("idhub预制前缀").base_url("${ENV(idhub_HOST)}").verify(False)

    teststeps = [
        Step(
            RunRequest("idhub预制前缀")
            .put("/api/prefixes/$prefix")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.msg", "success")
            .assert_equal("body.responseCode", 1)
        ),
    ]


if __name__ == "__main__":
    TestCaseIdhubhomeprefrix().test_start()
