# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/idhub/idhubreghandle-30.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseIdhubreghandle30(HttpRunner):

    config = Config("调用idhub接口创建标识").base_url("${ENV(idhub_HOST)}").verify(False)

    teststeps = [
        Step(
            RunRequest("调用idhub接口创建标识")
            .put("/api/handles/${idhub_biaoshi}")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Connection": "keep-alive",
                    "Content-Length": "297",
                    "Content-Type": "application/json",
                }
            )
            .with_json(
                [
                    {
                        "adminRead": "1",
                        "adminWrite": "1",
                        "data": {"format": "string", "value": "www.baidu.com"},
                        "index": 100,
                        "publicRead": "1",
                        "publicWrite": "0",
                        "references": [],
                        "timestamp": "2017-10-19 09:48:03",
                        "ttl": 86400,
                        "type": "URL",
                    }
                ]
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.msg", "success")
            .assert_equal("body.responseCode", 1)
        ),
    ]


if __name__ == "__main__":
    TestCaseIdhubreghandle30().test_start()
