# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/idhub/idhub-regist-handle-no-pass.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseIdhubRegistHandleNoPass(HttpRunner):

    config = Config("idhub注册标识-不通过").base_url("${ENV(idhub_HOST)}").verify(False)

    teststeps = [
        Step(
            RunRequest("idhub注册标识")
            .put("/api/handles/${idhub_biaoshi}")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
                }
            )
            .with_json(
                {
                    "index": 0,
                    "type": "URL",
                    "data": {"format": "string", "value": "www.baidu.com"},
                    "ttl": 86400,
                    "timestamp": "2017-10-19 09:48:03",
                    "references": [],
                    "adminRead": "1",
                    "adminWrite": "1",
                    "publicRead": "1",
                    "publicWrite": "0",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("body.msg", "标识不存在")
        ),
    ]


if __name__ == "__main__":
    TestCaseIdhubRegistHandleNoPass().test_start()
